In [1]:
!apt-get install -y r-base

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
r-base is already the newest version (4.6.0-4.2204.0).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

In [2]:
!R -e "install.packages(c('dplyr','readxl','igraph','tidyr'))"

R version 4.6.0 (2026-04-24) -- "Because it was There"
Copyright (C) 2026 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages(c('dplyr','readxl','igraph','tidyr'))
Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/dplyr_1.2.1.tar.gz'
trying URL 'https://cran.rstudio.com/src/contrib/readxl_1.5.0.tar.gz'
trying URL 'https://cran.rstudio.com/src/contrib/igraph_2.3.2.tar.gz'
trying URL 'https://cran.rstudio.com/src/contrib/tidyr_1.3.2.tar.gz'
* installing *source* package ‘dplyr’ ...
** this is package ‘dplyr’ version ‘1.2.1’
** package ‘dplyr’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C++ compiler: ‘g++ (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0’
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c chop.cpp -o chop.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c filter.cpp -o filter.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c funs.cpp -o funs.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c group_by.cpp -o group_by.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c group_data.cpp -o group_data.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c imports.cpp -o imports.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c init.cpp -o init.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c mask.cpp -o mask.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c mutate.cpp -o mutate.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c reconstruct.cpp -o reconstruct.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c slice.cpp -o slice.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG       -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c summarise.cpp -o summarise.o
g++ -std=gnu++20 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o dplyr.so chop.o filter.o funs.o group_by.o group_data.o imports.o init.o mask.o mutate.o reconstruct.o slice.o summarise.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/00LOCK-dplyr/00new/dplyr/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (dplyr)
* installing *source* package ‘readxl’ ...
** this is package ‘readxl’ version ‘1.5.0’
** package ‘readxl’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C compiler: ‘cc (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0’
using C++ compiler: ‘g++ (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0’
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG -Iunix -I. -I'/usr/lib/R/site-library/cpp11/include' -I'/usr/lib/R/site-library/progress/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c cpp11.cpp -o cpp11.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG -Iunix -I. -I'/usr/lib/R/site-library/cpp11/include' -I'/usr/lib/R/site-library/progress/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c XlsWorkBook.cpp -o XlsWorkBook.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG -Iunix -I. -I'/usr/lib/R/site-library/cpp11/include' -I'/usr/lib/R/site-library/progress/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c XlsxWorkBook.cpp -o XlsxWorkBook.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG -Iunix -I. -I'/usr/lib/R/site-library/cpp11/include' -I'/usr/lib/R/site-library/progress/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c zip.cpp -o zip.o
g++ -std=gnu++20 -I"/usr/share/R/include" -DNDEBUG -Iunix -I. -I'/usr/lib/R/site-library/cpp11/include' -I'/usr/lib/R/site-library/progress/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c Read.cpp -o Read.o
cc -I"/usr/share/R/include" -DNDEBUG -Iunix -I. -I'/usr/lib/R/site-library/cpp11/include' -I'/usr/lib/R/site-library/progress/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c cran.c -o cran.o
cc -I"/usr/share/R/include" -DNDEBUG -Iunix -I. -I'/usr/lib/R/site-library/cpp11/include' -I'/usr/lib/R/site-library/progress/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c libxls/xlstool.c -o libxls/xlstool.o
cc -I"/usr/share/R/include" -DNDEBUG -Iunix -I. -I'/usr/lib/R/site-library/cpp11/include' -I'/usr/lib/R/site-library/progress/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c libxls/endian.c -o libxls/endian.o
cc -I"/usr/share/R/include" -DNDEBUG -Iunix -I. -I'/usr/lib/R/site-library/cpp11/include' -I'/usr/lib/R/site-library/progress/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c libxls/ole.c -o libxls/ole.o
cc -I"/usr/share/R/include" -DNDEBUG -Iunix -I. -I'/usr/lib/R/site-library/cpp11/include' -I'/usr/lib/R/site-library/progress/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c libxls/xls.c -o libxls/xls.o
cc -I"/usr/share/R/include" -DNDEBUG -Iunix -I. -I'/usr/lib/R/site-library/cpp11/include' -I'/usr/lib/R/site-library/progress/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c libxls/locale.c -o libxls/locale.o
g++ -std=gnu++20 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o readxl.so cpp11.o XlsWorkBook.o XlsxWorkBook.o zip.o Read.o cran.o libxls/xlstool.o libxls/endian.o libxls/ole.o libxls/xls.o libxls/locale.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/00LOCK-readxl/00new/readxl/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (readxl)
* installing *source* package ‘igraph’ ...
** this is package ‘igraph’ version ‘2.3.2’
** package ‘igraph’ successfully unpacked and MD5 sums checked
** using staged installation
libxml2 include directories: -I/usr/include/libxml2
libxml2 library link flags: -lxml2
Using vendored GLPK
** libs
using C compiler: ‘cc (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0’
using C++ compiler: ‘g++ (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0’
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dgetv0.f -o vendor/arpack/dgetv0.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dlaqrb.f -o vendor/arpack/dlaqrb.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dmout.f -o vendor/arpack/dmout.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dnaitr.f -o vendor/arpack/dnaitr.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dnapps.f -o vendor/arpack/dnapps.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dnaup2.f -o vendor/arpack/dnaup2.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dnaupd.f -o vendor/arpack/dnaupd.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dnconv.f -o vendor/arpack/dnconv.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dneigh.f -o vendor/arpack/dneigh.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dneupd.f -o vendor/arpack/dneupd.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dngets.f -o vendor/arpack/dngets.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dsaitr.f -o vendor/arpack/dsaitr.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dsapps.f -o vendor/arpack/dsapps.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dsaup2.f -o vendor/arpack/dsaup2.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dsaupd.f -o vendor/arpack/dsaupd.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dsconv.f -o vendor/arpack/dsconv.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dseigt.f -o vendor/arpack/dseigt.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dsesrt.f -o vendor/arpack/dsesrt.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dseupd.f -o vendor/arpack/dseupd.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dsgets.f -o vendor/arpack/dsgets.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dsortc.f -o vendor/arpack/dsortc.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dsortr.f -o vendor/arpack/dsortr.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dstatn.f -o vendor/arpack/dstatn.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dstats.f -o vendor/arpack/dstats.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dstqrb.f -o vendor/arpack/dstqrb.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/dvout.f -o vendor/arpack/dvout.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/ivout.f -o vendor/arpack/ivout.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/second.f -o vendor/arpack/second.o
f77 -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong  -c vendor/arpack/wrap.f -o vendor/arpack/wrap.o
cc -I"/usr/share/R/include" -DNDEBUG -DUSING_R -I. -Ivendor -Ivendor/cigraph/src -Ivendor/cigraph/include -Ivendor/cigraph/vendor -Ivendor/io/parsers  -I/usr/include/libxml2 -DHAVE_LIBXML -Ivendor/cigraph/vendor/glpk -Ivendor/cigraph/vendor/glpk/env -Ivendor/cigraph/vendor/glpk/minisat -Ivendor/cigraph/vendor/glpk/misc -Ivendor/cigraph/vendor/glpk/draft -Ivendor/cigraph/vendor/glpk/npp -Ivendor/cigraph/vendor/glpk/api -Ivendor/cigraph/vendor/glpk/mpl -Ivendor/cigraph/vendor/glpk/bflib -Ivendor/cigraph/vendor/glpk/amd -Ivendor/cigraph/vendor/glpk/simplex -Ivendor/cigraph/vendor/glpk/colamd -DNDEBUG -DIGRAPH_THREAD_LOCAL= -DPRPACK_IGRAPH_SUPPORT -DHAVE_GFORTRAN=1 -D_GNU_SOURCE=1 -I'/usr/lib/R/site-library/cpp11/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c vendor/cigraph/src/centrality/betweenness.c -o vendor/cigraph/src/centrality/betweenness.o
cc -I"/usr/share/R/include" -DNDEBUG -DUSING_R -I. -Ivendor -Ivendor/cigraph/src -Ivendor/cigraph/include -Ivendor/cigraph/vendor -Ivendor/io/parsers  -I/usr/include/libxml2 -DHAVE_LIBXML -Ivendor/cigraph/vendor/glpk -Ivendor/cigraph/vendor/glpk/env -Ivendor/cigraph/vendor/glpk/minisat -Ivendor/cigraph/vendor/glpk/misc -Ivendor/cigraph/vendor/glpk/draft -Ivendor/cigraph/vendor/glpk/npp -Ivendor/cigraph/vendor/glpk/api -Ivendor/cigraph/vendor/glpk/mpl -Ivendor/cigraph/vendor/glpk/bflib -Ivendor/cigraph/vendor/glpk/amd -Ivendor/cigraph/vendor/glpk/simplex -Ivendor/cigraph/vendor/glpk/colamd -DNDEBUG -DIGRAPH_THREAD_LOCAL= -DPRPACK_IGRAPH_SUPPORT -DHAVE_GFORTRAN=1 -D_GNU_SOURCE=1 -I'/usr/lib/R/site-library/cpp11/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c vendor/cigraph/src/centrality/centrality_other.c -o vendor/cigraph/src/centrality/centrality_other.o
cc -I"/usr/share/R/include" -DNDEBUG -DUSING_R -I. -Ivendor -Ivendor/cigraph/src -Ivendor/cigraph/include -Ivendor/cigraph/vendor -Ivendor/io/parsers  -I/usr/include/libxml2 -DHAVE_LIBXML -Ivendor/cigraph/vendor/glpk -Ivendor/cigraph/vendor/glpk/env -Ivendor/cigraph/vendor/glpk/minisat -Ivendor/cigraph/vendor/glpk/misc -Ivendor/cigraph/vendor/glpk/draft -Ivendor/cigraph/vendor/glpk/npp -Ivendor/cigraph/vendor/glpk/api -Ivendor/cigraph/vendor/glpk/mpl -Ivendor/cigraph/vendor/glpk/bflib -Ivendor/cigraph/vendor/glpk/amd -Ivendor/cigraph/vendor/glpk/simplex -Ivendor/cigraph/vendor/glpk/colamd -DNDEBUG -DIGRAPH_THREAD_LOCAL= -DPRPACK_IGRAPH_SUPPORT -DHAVE_GFORTRAN=1 -D_GNU_SOURCE=1 -I'/usr/lib/R/site-library/cpp11/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c vendor/cigraph/src/centrality/centralization.c -o vendor/cigraph/src/centrality/centralization.o
cc -I"/usr/share/R/include" -DNDEBUG -DUSING_R -I. -Ivendor -Ivendor/cigraph/src -Ivendor/cigraph/include -Ivendor/cigraph/vendor -Ivendor/io/parsers  -I/usr/include/libxml2 -DHAVE_LIBXML -Ivendor/cigraph/vendor/glpk -Ivendor/cigraph/vendor/glpk/env -Ivendor/cigraph/vendor/glpk/minisat -Ivendor/cigraph/vendor/glpk/misc -Ivendor/cigraph/vendor/glpk/draft -Ivendor/cigraph/vendor/glpk/npp -Ivendor/cigraph/vendor/glpk/api -Ivendor/cigraph/vendor/glpk/mpl -Ivendor/cigraph/vendor/glpk/bflib -Ivendor/cigraph/vendor/glpk/amd -Ivendor/cigraph/vendor/glpk/simplex -Ivendor/cigraph/vendor/glpk/colamd -DNDEBUG -DIGRAPH_THREAD_LOCAL= -DPRPACK_IGRAPH_SUPPORT -DHAVE_GFORTRAN=1 -D_GNU_SOURCE=1 -I'/usr/lib/R/site-library/cpp11/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-gN72Ro/r-base-4.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c vendor/cigraph/src/centrality/closeness.c -o vendor/cigraph/src/centrality/closeness.o

In [3]:
!apt-get update
!apt-get install -y r-base

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:5 https://cli.github.com/packages stable InRelease [3,917 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,307 kB]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,221 kB]
Get:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [4,026 kB]
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:13 https://cli.github.com/packages stable/main amd64 Packages [354 B]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,495 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,612 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,361 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.6 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [82.8 kB]
Get:19 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.4 MB]
Get:20 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.6 kB]
Get:21 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,069 kB]
Fetched 40.1 MB in 4s (10.3 MB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
r-base is already the newest version (4.6.0-4.2204.0).
0 upgraded, 0 newly installed, 0 to remove and 43 not upgraded.

In [4]:
!git clone https://github.com/OmerKahveci03/Gene-Normalization-and-Mapping.git

Cloning into 'Gene-Normalization-and-Mapping'...
remote: Enumerating objects: 847, done.
remote: Counting objects: 100% (436/436), done.
remote: Compressing objects: 100% (401/401), done.
remote: Total 847 (delta 47), reused 416 (delta 34), pack-reused 411 (from 2)
Receiving objects: 100% (847/847), 105.82 MiB | 17.52 MiB/s, done.
Resolving deltas: 100% (342/342), done.
Updating files: 100% (569/569), done.

In [5]:
!find Gene-Normalization-and-Mapping -type f | head -100

Gene-Normalization-and-Mapping/.gitignore
Gene-Normalization-and-Mapping/src/final_visuals.R
Gene-Normalization-and-Mapping/src/gene_networks.R
Gene-Normalization-and-Mapping/src/drug_efficacy.R
Gene-Normalization-and-Mapping/src/normalize_all_tissues.R
Gene-Normalization-and-Mapping/src/normalize_tissue.R
Gene-Normalization-and-Mapping/src/algorithm_0.R
Gene-Normalization-and-Mapping/src/null_algorithm.R
Gene-Normalization-and-Mapping/src/algorithm_1.R
Gene-Normalization-and-Mapping/src/utility.R
Gene-Normalization-and-Mapping/src/age_indexing/webscrape.py
Gene-Normalization-and-Mapping/src/age_indexing/compare_algorithms.py
Gene-Normalization-and-Mapping/src/age_indexing/create_visuals.py
Gene-Normalization-and-Mapping/src/age_indexing/z_score_visuals.py
Gene-Normalization-and-Mapping/src/age_based_influence.R
Gene-Normalization-and-Mapping/README.md
Gene-Normalization-and-Mapping/.git/info/exclude
Gene-Normalization-and-Mapping/.git/logs/HEAD
Gene-Normalization-and-Mapping/.git/logs/refs/heads/main
Gene-Normalization-and-Mapping/.git/logs/refs/remotes/origin/HEAD
Gene-Normalization-and-Mapping/.git/HEAD
Gene-Normalization-and-Mapping/.git/description
Gene-Normalization-and-Mapping/.git/hooks/pre-commit.sample
Gene-Normalization-and-Mapping/.git/hooks/pre-merge-commit.sample
Gene-Normalization-and-Mapping/.git/hooks/pre-rebase.sample
Gene-Normalization-and-Mapping/.git/hooks/push-to-checkout.sample
Gene-Normalization-and-Mapping/.git/hooks/pre-applypatch.sample
Gene-Normalization-and-Mapping/.git/hooks/applypatch-msg.sample
Gene-Normalization-and-Mapping/.git/hooks/post-update.sample
Gene-Normalization-and-Mapping/.git/hooks/pre-receive.sample
Gene-Normalization-and-Mapping/.git/hooks/fsmonitor-watchman.sample
Gene-Normalization-and-Mapping/.git/hooks/prepare-commit-msg.sample
Gene-Normalization-and-Mapping/.git/hooks/update.sample
Gene-Normalization-and-Mapping/.git/hooks/commit-msg.sample
Gene-Normalization-and-Mapping/.git/hooks/pre-push.sample
Gene-Normalization-and-Mapping/.git/refs/heads/main
Gene-Normalization-and-Mapping/.git/refs/remotes/origin/HEAD
Gene-Normalization-and-Mapping/.git/config
Gene-Normalization-and-Mapping/.git/index
Gene-Normalization-and-Mapping/.git/packed-refs
Gene-Normalization-and-Mapping/.git/objects/pack/pack-ec166eb38d5c9d4f2b0b50f1d5e48baeabbb5c78.idx
Gene-Normalization-and-Mapping/.git/objects/pack/pack-ec166eb38d5c9d4f2b0b50f1d5e48baeabbb5c78.pack
Gene-Normalization-and-Mapping/data/normalized/normalized_artery_coronary.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_brain_anterior_cingulate_cortex_ba24.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_thyroid.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_vagina.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_breast_mammary_tissue.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_uterus.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_brain_putamen_basal_ganglia.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_cells_ebv-transformed_lymphocytes.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_colon_transverse.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_heart_left_ventricle.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_colon_sigmoid.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_brain_caudate_basal_ganglia.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_brain_substantia_nigra.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_pancreas.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_spleen.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_stomach.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_heart_atrial_appendage.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_adrenal_gland.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_brain_hippocampus.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_brain_spinal_cord_cervical_c-1).csv
Gene-Normalization-and-Mapping/data/normalized/normalized_prostate.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_brain_cortex.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_adipose_visceral_omentum.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_brain_amygdala.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_brain_cerebellar_hemisphere.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_esophagus_gastroesophageal_junction.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_adipose_subcutaneous.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_testis.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_minor_salivary_gland.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_brain_frontal_cortex_ba9.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_skin_not_sun_exposed_suprapubic.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_brain_nucleus_accumbens_basal ganglia.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_brain_cerebellum.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_nerve_tibial.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_muscle_skeletal.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_lung.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_brain_hypothalamus.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_skin_sun_exposed_lower_leg.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_small_intestine_terminal_ileum.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_liver.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_ovary.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_cells_cultured_fibroblasts.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_kidney_cortex.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_pituitary.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_whole_blood.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_esophagus_mucosa.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_artery_aorta.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_esophagus_muscularis.csv
Gene-Normalization-and-Mapping/data/normalized/normalized_artery_tibial.csv
Gene-Normalization-and-Mapping/data/age_indexes/max_brain_frontal_cortex_ba9_plot.png
Gene-Normalization-and-Mapping/data/age_indexes/max_pancreas_plot.png
Gene-Normalization-and-Mapping/data/age_indexes/min_artery_tibial_plot.png
Gene-Normalization-and-Mapping/data/age_indexes/max_heart_atrial_appendage_plot.png
Gene-Normalization-and-Mapping/data/age_indexes/max_heart_left_ventricle_plot.png
Gene-Normalization-and-Mapping/data/age_indexes/min_brain_cerebellum_plot.png
Gene-Normalization-and-Mapping/data/age_indexes/max_ovary_plot.png
Gene-Normalization-and-Mapping/data/age_indexes/min_brain_spinal_cord_cervical_c-1)_plot.png
Gene-Normalization-and-Mapping/data/age_indexes/max_skin_not_sun_exposed_suprapubic_plot.png

In [6]:
import pandas as pd

disease = pd.read_csv("Gene-Normalization-and-Mapping/data/drug/bpco_gene_disease_associations.csv")
drug = pd.read_csv("Gene-Normalization-and-Mapping/data/drug/bpco_drug_gene_associations.csv")

print("Disease file:")
print(disease.head())
print(disease.columns)
print(disease.shape)

print("\nDrug file:")
print(drug.head())
print(drug.columns)
print(drug.shape)

Disease file:
  geneSymbol          diseaseName
0   SERPINA1  Pulmonary Emphysema
1      TGFB1  Pulmonary Emphysema
2      MMP12  Pulmonary Emphysema
3      EPHX1  Pulmonary Emphysema
4      HMOX1  Pulmonary Emphysema
Index(['geneSymbol', 'diseaseName'], dtype='object')
(261, 2)

Drug file:
              drug_name gene_name
0  CHEMBL:CHEMBL1833984     PPARG
1             NERATINIB       KDR
2          BENZENETHIOL       JUN
3             NOSCAPINE     HIF1A
4   CHEMBL:CHEMBL601367     SMAD3
Index(['drug_name', 'gene_name'], dtype='object')
(5448, 2)

In [7]:
import pandas as pd

disease = pd.read_csv(
    "Gene-Normalization-and-Mapping/data/drug/bpco_gene_disease_associations.csv"
)

drug = pd.read_csv(
    "Gene-Normalization-and-Mapping/data/drug/bpco_drug_gene_associations.csv"
)

print("Disease columns:")
print(disease.columns)

print("\nDisease shape:")
print(disease.shape)

print("\nDisease head:")
print(disease.head())

print("\nDrug columns:")
print(drug.columns)

print("\nDrug shape:")
print(drug.shape)

print("\nDrug head:")
print(drug.head())

Disease columns:
Index(['geneSymbol', 'diseaseName'], dtype='object')

Disease shape:
(261, 2)

Disease head:
  geneSymbol          diseaseName
0   SERPINA1  Pulmonary Emphysema
1      TGFB1  Pulmonary Emphysema
2      MMP12  Pulmonary Emphysema
3      EPHX1  Pulmonary Emphysema
4      HMOX1  Pulmonary Emphysema

Drug columns:
Index(['drug_name', 'gene_name'], dtype='object')

Drug shape:
(5448, 2)

Drug head:
              drug_name gene_name
0  CHEMBL:CHEMBL1833984     PPARG
1             NERATINIB       KDR
2          BENZENETHIOL       JUN
3             NOSCAPINE     HIF1A
4   CHEMBL:CHEMBL601367     SMAD3

In [14]:
from pathlib import Path

output_excel = Path("Gene-Normalization-and-Mapping/data/drug/bpco_drug_gene_associations.xlsx")

In [15]:
!cp /content/bpco_gene_disease_associations.csv /content/Gene-Normalization-and-Mapping/data/
!cp /content/bpco_drug_gene_associations.csv /content/Gene-Normalization-and-Mapping/data/

cp: cannot stat '/content/bpco_gene_disease_associations.csv': No such file or directory
cp: cannot stat '/content/bpco_drug_gene_associations.csv': No such file or directory

In [13]:
!cp Gene-Normalization-and-Mapping/src/drug_efficacy.R Gene-Normalization-and-Mapping/src/drug_efficacy_bpco.R

cp: cannot stat 'Gene-Normalization-and-Mapping/src/drug_efficacy.R': No such file or directory

In [12]:
!cp Gene-Normalization-and-Mapping/src/drug_efficacy.R Gene-Normalization-and-Mapping/src/drug_efficacy_BPCO.R

cp: cannot stat 'Gene-Normalization-and-Mapping/src/drug_efficacy.R': No such file or directory

In [10]:
%cd Gene-Normalization-and-Mapping/src
!Rscript drug_efficacy_BPCO.R

/content/Gene-Normalization-and-Mapping/src
Fatal error: cannot open file 'drug_efficacy_BPCO.R': No such file or directory

In [16]:
%cd /content/Gene-Normalization-and-Mapping

/content/Gene-Normalization-and-Mapping

In [17]:
!ls
!ls data

data  README.md  src  visuals
age_indexes			 bpco_gene_disease_associations.csv  mapped
bpco_drug_gene_associations.csv  drug				     normalized

In [18]:
!cp bpco_gene_disease_associations.csv data/
!cp bpco_drug_gene_associations.csv data/

cp: cannot stat 'bpco_gene_disease_associations.csv': No such file or directory
cp: cannot stat 'bpco_drug_gene_associations.csv': No such file or directory

In [19]:
!ls data | grep bpco

bpco_drug_gene_associations.csv
bpco_gene_disease_associations.csv

In [22]:
import pandas as pd

disease = pd.read_csv("data/bpco_gene_disease_associations.csv")
drug = pd.read_csv("data/bpco_drug_gene_associations.csv")

print(disease.shape)
print(drug.shape)

print(disease.columns.tolist())
print(drug.columns.tolist())

(261, 2)
(5448, 2)
['geneSymbol', 'diseaseName']
['drug_name', 'gene_name']

In [23]:
import pandas as pd

disease = pd.read_csv("data/bpco_gene_disease_associations.csv")
drug = pd.read_csv("data/bpco_drug_gene_associations.csv")

print("Disease shape:", disease.shape)
print("Drug shape:", drug.shape)

print("Disease columns:", disease.columns.tolist())
print("Drug columns:", drug.columns.tolist())

print("Unique BPCO genes:", disease["geneSymbol"].nunique())
print("Unique BPCO drugs:", drug["drug_name"].nunique())

display(disease.head())
display(drug.head())

Disease shape: (261, 2)
Drug shape: (5448, 2)
Disease columns: ['geneSymbol', 'diseaseName']
Drug columns: ['drug_name', 'gene_name']
Unique BPCO genes: 209
Unique BPCO drugs: 3657

  geneSymbol          diseaseName
0   SERPINA1  Pulmonary Emphysema
1      TGFB1  Pulmonary Emphysema
2      MMP12  Pulmonary Emphysema
3      EPHX1  Pulmonary Emphysema
4      HMOX1  Pulmonary Emphysema

              drug_name gene_name
0  CHEMBL:CHEMBL1833984     PPARG
1             NERATINIB       KDR
2          BENZENETHIOL       JUN
3             NOSCAPINE     HIF1A
4   CHEMBL:CHEMBL601367     SMAD3

In [24]:
!cp bpco_gene_disease_associations.csv data/
!cp bpco_drug_gene_associations.csv data/

cp: cannot stat 'bpco_gene_disease_associations.csv': No such file or directory
cp: cannot stat 'bpco_drug_gene_associations.csv': No such file or directory

In [25]:
import pandas as pd

disease = pd.read_csv("data/bpco_gene_disease_associations.csv")
drug = pd.read_csv("data/bpco_drug_gene_associations.csv")

print("Disease shape:", disease.shape)
print("Drug shape:", drug.shape)
print("Disease columns:", disease.columns.tolist())
print("Drug columns:", drug.columns.tolist())
print("Unique BPCO genes:", disease["geneSymbol"].nunique())
print("Unique BPCO drugs:", drug["drug_name"].nunique())

Disease shape: (261, 2)
Drug shape: (5448, 2)
Disease columns: ['geneSymbol', 'diseaseName']
Drug columns: ['drug_name', 'gene_name']
Unique BPCO genes: 209
Unique BPCO drugs: 3657

In [26]:
%load_ext rpy2.ipython

In [27]:
%%R

library(dplyr)

disease_gene_path <- "data/bpco_gene_disease_associations.csv"
drug_gene_path <- "data/bpco_drug_gene_associations.csv"

disease_gene <- read.csv(disease_gene_path, stringsAsFactors = FALSE)
drug_gene <- read.csv(drug_gene_path, stringsAsFactors = FALSE)

disease_gene$geneSymbol <- toupper(trimws(disease_gene$geneSymbol))
drug_gene$gene_name <- toupper(trimws(drug_gene$gene_name))

disease_genes <- unique(na.omit(disease_gene$geneSymbol))

drug_gene_filtered <- drug_gene %>%
  filter(gene_name %in% disease_genes) %>%
  select(drug_name, gene_name) %>%
  distinct()

cat("BPCO disease-gene rows:", nrow(disease_gene), "\n")
cat("Unique BPCO disease genes:", length(disease_genes), "\n")
cat("BPCO drug-gene rows:", nrow(drug_gene_filtered), "\n")
cat("Unique BPCO drugs:", length(unique(drug_gene_filtered$drug_name)), "\n")

write.csv(disease_gene, "data/bpco_disease_genes_clean.csv", row.names = FALSE)
write.csv(drug_gene_filtered, "data/bpco_drug_gene_filtered_clean.csv", row.names = FALSE)

BPCO disease-gene rows: 261
Unique BPCO disease genes: 209
BPCO drug-gene rows: 5448
Unique BPCO drugs: 3657

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [28]:
%cd /content/Gene-Normalization-and-Mapping

!find data -maxdepth 2 -type f

/content/Gene-Normalization-and-Mapping
data/normalized/normalized_artery_coronary.csv
data/normalized/normalized_brain_anterior_cingulate_cortex_ba24.csv
data/normalized/normalized_thyroid.csv
data/normalized/normalized_vagina.csv
data/normalized/normalized_breast_mammary_tissue.csv
data/normalized/normalized_uterus.csv
data/normalized/normalized_brain_putamen_basal_ganglia.csv
data/normalized/normalized_cells_ebv-transformed_lymphocytes.csv
data/normalized/normalized_colon_transverse.csv
data/normalized/normalized_heart_left_ventricle.csv
data/normalized/normalized_colon_sigmoid.csv
data/normalized/normalized_brain_caudate_basal_ganglia.csv
data/normalized/normalized_brain_substantia_nigra.csv
data/normalized/normalized_pancreas.csv
data/normalized/normalized_spleen.csv
data/normalized/normalized_stomach.csv
data/normalized/normalized_heart_atrial_appendage.csv
data/normalized/normalized_adrenal_gland.csv
data/normalized/normalized_brain_hippocampus.csv
data/normalized/normalized_brain_spinal_cord_cervical_c-1).csv
data/normalized/normalized_prostate.csv
data/normalized/normalized_brain_cortex.csv
data/normalized/normalized_adipose_visceral_omentum.csv
data/normalized/normalized_brain_amygdala.csv
data/normalized/normalized_brain_cerebellar_hemisphere.csv
data/normalized/normalized_esophagus_gastroesophageal_junction.csv
data/normalized/normalized_adipose_subcutaneous.csv
data/normalized/normalized_testis.csv
data/normalized/normalized_minor_salivary_gland.csv
data/normalized/normalized_brain_frontal_cortex_ba9.csv
data/normalized/normalized_skin_not_sun_exposed_suprapubic.csv
data/normalized/normalized_brain_nucleus_accumbens_basal ganglia.csv
data/normalized/normalized_brain_cerebellum.csv
data/normalized/normalized_nerve_tibial.csv
data/normalized/normalized_muscle_skeletal.csv
data/normalized/normalized_lung.csv
data/normalized/normalized_brain_hypothalamus.csv
data/normalized/normalized_skin_sun_exposed_lower_leg.csv
data/normalized/normalized_small_intestine_terminal_ileum.csv
data/normalized/normalized_liver.csv
data/normalized/normalized_ovary.csv
data/normalized/normalized_cells_cultured_fibroblasts.csv
data/normalized/normalized_kidney_cortex.csv
data/normalized/normalized_pituitary.csv
data/normalized/normalized_whole_blood.csv
data/normalized/normalized_esophagus_mucosa.csv
data/normalized/normalized_artery_aorta.csv
data/normalized/normalized_esophagus_muscularis.csv
data/normalized/normalized_artery_tibial.csv
data/bpco_drug_gene_filtered_clean.csv
data/bpco_drug_gene_associations.csv
data/bpco_disease_genes_clean.csv
data/bpco_gene_disease_associations.csv
data/age_indexes/max_brain_frontal_cortex_ba9_plot.png
data/age_indexes/max_pancreas_plot.png
data/age_indexes/min_artery_tibial_plot.png
data/age_indexes/max_heart_atrial_appendage_plot.png
data/age_indexes/max_heart_left_ventricle_plot.png
data/age_indexes/min_brain_cerebellum_plot.png
data/age_indexes/max_ovary_plot.png
data/age_indexes/min_brain_spinal_cord_cervical_c-1)_plot.png
data/age_indexes/max_skin_not_sun_exposed_suprapubic_plot.png
data/age_indexes/max_lung_plot.png
data/age_indexes/min_brain_substantia_nigra_plot.png
data/age_indexes/min_breast_mammary_tissue_plot.png
data/age_indexes/min_adipose_subcutaneous_plot.png
data/age_indexes/max_artery_aorta_plot.png
data/age_indexes/min_adrenal_gland_plot.png
data/age_indexes/min_pituitary_plot.png
data/age_indexes/min_lung_plot.png
data/age_indexes/min_muscle_skeletal_plot.png
data/age_indexes/min_small_intestine_terminal_ileum_plot.png
data/age_indexes/min_brain_amygdala_plot.png
data/age_indexes/max_stomach_plot.png
data/age_indexes/min_esophagus_muscularis_plot.png
data/age_indexes/max_breast_mammary_tissue_plot.png
data/age_indexes/min_spleen_plot.png
data/age_indexes/max_spleen_plot.png
data/age_indexes/max_esophagus_mucosa_plot.png
data/age_indexes/max_brain_cortex_plot.png
data/age_indexes/min_whole_blood_plot.png
data/age_indexes/pubmed_genes.xlsx
data/age_indexes/max_pituitary_plot.png
data/age_indexes/max_vagina_plot.png
data/age_indexes/max_brain_anterior_cingulate_cortex_ba24_plot.png
data/age_indexes/min_brain_caudate_basal_ganglia_plot.png
data/age_indexes/min_stomach_plot.png
data/age_indexes/min_heart_left_ventricle_plot.png
data/age_indexes/min_brain_cortex_plot.png
data/age_indexes/max_whole_blood_plot.png
data/age_indexes/max_skin_sun_exposed_lower_leg_plot.png
data/age_indexes/max_liver_plot.png
data/age_indexes/min_nerve_tibial_plot.png
data/age_indexes/max_adrenal_gland_plot.png
data/age_indexes/min_colon_transverse_plot.png
data/age_indexes/max_brain_nucleus_accumbens_basal ganglia_plot.png
data/age_indexes/min_brain_cerebellar_hemisphere_plot.png
data/age_indexes/min_pancreas_plot.png
data/age_indexes/max_artery_coronary_plot.png
data/age_indexes/min_skin_sun_exposed_lower_leg_plot.png
data/age_indexes/max_brain_cerebellum_plot.png
data/age_indexes/min_brain_hypothalamus_plot.png
data/age_indexes/max_uterus_plot.png
data/age_indexes/min_heart_atrial_appendage_plot.png
data/age_indexes/min_minor_salivary_gland_plot.png
data/age_indexes/max_artery_tibial_plot.png
data/age_indexes/min_brain_putamen_basal_ganglia_plot.png
data/age_indexes/max_colon_sigmoid_plot.png
data/age_indexes/max_brain_substantia_nigra_plot.png
data/age_indexes/max_minor_salivary_gland_plot.png
data/age_indexes/max_brain_hypothalamus_plot.png
data/age_indexes/min_vagina_plot.png
data/age_indexes/min_prostate_plot.png
data/age_indexes/min_ovary_plot.png
data/age_indexes/max_brain_spinal_cord_cervical_c-1)_plot.png
data/age_indexes/max_thyroid_plot.png
data/age_indexes/max_esophagus_muscularis_plot.png
data/age_indexes/max_brain_hippocampus_plot.png
data/age_indexes/min_artery_coronary_plot.png
data/age_indexes/max_adipose_visceral_omentum_plot.png
data/age_indexes/max_brain_cerebellar_hemisphere_plot.png
data/age_indexes/min_adipose_visceral_omentum_plot.png
data/age_indexes/max_nerve_tibial_plot.png
data/age_indexes/min_liver_plot.png
data/age_indexes/max_esophagus_gastroesophageal_junction_plot.png
data/age_indexes/max_prostate_plot.png
data/age_indexes/min_cells_cultured_fibroblasts_plot.png
data/age_indexes/max_colon_transverse_plot.png
data/age_indexes/max_brain_caudate_basal_ganglia_plot.png
data/age_indexes/max_brain_amygdala_plot.png
data/age_indexes/min_esophagus_mucosa_plot.png
data/age_indexes/max_cells_cultured_fibroblasts_plot.png
data/age_indexes/max_brain_putamen_basal_ganglia_plot.png
data/age_indexes/min_testis_plot.png
data/age_indexes/min_brain_anterior_cingulate_cortex_ba24_plot.png
data/age_indexes/min_esophagus_gastroesophageal_junction_plot.png
data/age_indexes/min_brain_frontal_cortex_ba9_plot.png
data/age_indexes/min_brain_nucleus_accumbens_basal ganglia_plot.png
data/age_indexes/max_cells_ebv-transformed_lymphocytes_plot.png
data/age_indexes/min_cells_ebv-transformed_lymphocytes_plot.png
data/age_indexes/max_muscle_skeletal_plot.png
data/age_indexes/min_artery_aorta_plot.png
data/age_indexes/min_thyroid_plot.png
data/age_indexes/max_adipose_subcutaneous_plot.png
data/age_indexes/min_skin_not_sun_exposed_suprapubic_plot.png
data/age_indexes/min_colon_sigmoid_plot.png
data/age_indexes/min_uterus_plot.png
data/age_indexes/min_brain_hippocampus_plot.png
data/age_indexes/max_small_intestine_terminal_ileum_plot.png
data/age_indexes/max_testis_plot.png
data/drug/filtered_drug_gene_dataset.xlsx
data/drug/filtered_neurodegenerative_diseases.csv
data/drug/efficacy-alzheimers.csv
data/drug/efficacy-multiple sclerosis.csv
data/drug/efficacy-parkinson.csv
data/drug/filtered_drug_gene_dataset.csv

In [29]:
!find . -type f | grep -Ei "gtex|trrust|expression|network|gene|drug|efficacy|rds|csv|tsv"

./src/gene_networks.R
./src/drug_efficacy.R
./src/drug_efficacy_bpco.R
./data/normalized/normalized_artery_coronary.csv
./data/normalized/normalized_brain_anterior_cingulate_cortex_ba24.csv
./data/normalized/normalized_thyroid.csv
./data/normalized/normalized_vagina.csv
./data/normalized/normalized_breast_mammary_tissue.csv
./data/normalized/normalized_uterus.csv
./data/normalized/normalized_brain_putamen_basal_ganglia.csv
./data/normalized/normalized_cells_ebv-transformed_lymphocytes.csv
./data/normalized/normalized_colon_transverse.csv
./data/normalized/normalized_heart_left_ventricle.csv
./data/normalized/normalized_colon_sigmoid.csv
./data/normalized/normalized_brain_caudate_basal_ganglia.csv
./data/normalized/normalized_brain_substantia_nigra.csv
./data/normalized/normalized_pancreas.csv
./data/normalized/normalized_spleen.csv
./data/normalized/normalized_stomach.csv
./data/normalized/normalized_heart_atrial_appendage.csv
./data/normalized/normalized_adrenal_gland.csv
./data/normalized/normalized_brain_hippocampus.csv
./data/normalized/normalized_brain_spinal_cord_cervical_c-1).csv
./data/normalized/normalized_prostate.csv
./data/normalized/normalized_brain_cortex.csv
./data/normalized/normalized_adipose_visceral_omentum.csv
./data/normalized/normalized_brain_amygdala.csv
./data/normalized/normalized_brain_cerebellar_hemisphere.csv
./data/normalized/normalized_esophagus_gastroesophageal_junction.csv
./data/normalized/normalized_adipose_subcutaneous.csv
./data/normalized/normalized_testis.csv
./data/normalized/normalized_minor_salivary_gland.csv
./data/normalized/normalized_brain_frontal_cortex_ba9.csv
./data/normalized/normalized_skin_not_sun_exposed_suprapubic.csv
./data/normalized/normalized_brain_nucleus_accumbens_basal ganglia.csv
./data/normalized/normalized_brain_cerebellum.csv
./data/normalized/normalized_nerve_tibial.csv
./data/normalized/normalized_muscle_skeletal.csv
./data/normalized/normalized_lung.csv
./data/normalized/normalized_brain_hypothalamus.csv
./data/normalized/normalized_skin_sun_exposed_lower_leg.csv
./data/normalized/normalized_small_intestine_terminal_ileum.csv
./data/normalized/normalized_liver.csv
./data/normalized/normalized_ovary.csv
./data/normalized/normalized_cells_cultured_fibroblasts.csv
./data/normalized/normalized_kidney_cortex.csv
./data/normalized/normalized_pituitary.csv
./data/normalized/normalized_whole_blood.csv
./data/normalized/normalized_esophagus_mucosa.csv
./data/normalized/normalized_artery_aorta.csv
./data/normalized/normalized_esophagus_muscularis.csv
./data/normalized/normalized_artery_tibial.csv
./data/bpco_drug_gene_filtered_clean.csv
./data/bpco_drug_gene_associations.csv
./data/bpco_disease_genes_clean.csv
./data/bpco_gene_disease_associations.csv
./data/age_indexes/pubmed_genes.xlsx
./data/age_indexes/excel_files/pubmed_genes.xlsx
./data/drug/filtered_drug_gene_dataset.xlsx
./data/drug/filtered_neurodegenerative_diseases.csv
./data/drug/efficacy-alzheimers.csv
./data/drug/efficacy-multiple sclerosis.csv
./data/drug/efficacy-parkinson.csv
./data/drug/filtered_drug_gene_dataset.csv
./data/mapped/30/mapped_artery_tibial_30.csv
./data/mapped/30/mapped_liver_30.csv
./data/mapped/30/mapped_nerve_tibial_30.csv
./data/mapped/30/mapped_colon_transverse_30.csv
./data/mapped/30/mapped_adrenal_gland_30.csv
./data/mapped/30/mapped_brain_nucleus_accumbens_basal ganglia_30.csv
./data/mapped/30/mapped_heart_atrial_appendage_30.csv
./data/mapped/30/mapped_brain_hypothalamus_30.csv
./data/mapped/30/mapped_whole_blood_30.csv
./data/mapped/30/mapped_brain_anterior_cingulate_cortex_ba24_30.csv
./data/mapped/30/mapped_brain_cerebellum_30.csv
./data/mapped/30/mapped_esophagus_muscularis_30.csv
./data/mapped/30/mapped_ovary_30.csv
./data/mapped/30/mapped_lung_30.csv
./data/mapped/30/mapped_testis_30.csv
./data/mapped/30/mapped_brain_putamen_basal_ganglia_30.csv
./data/mapped/30/mapped_uterus_30.csv
./data/mapped/30/mapped_artery_coronary_30.csv
./data/mapped/30/mapped_minor_salivary_gland_30.csv
./data/mapped/30/mapped_spleen_30.csv
./data/mapped/30/mapped_stomach_30.csv
./data/mapped/30/mapped_thyroid_30.csv
./data/mapped/30/mapped_pancreas_30.csv
./data/mapped/30/mapped_cells_ebv-transformed_lymphocytes_30.csv
./data/mapped/30/mapped_esophagus_gastroesophageal_junction_30.csv
./data/mapped/30/mapped_skin_sun_exposed_lower_leg_30.csv
./data/mapped/30/mapped_brain_spinal_cord_cervical_c-1)_30.csv
./data/mapped/30/mapped_brain_caudate_basal_ganglia_30.csv
./data/mapped/30/mapped_brain_frontal_cortex_ba9_30.csv
./data/mapped/30/mapped_brain_hippocampus_30.csv
./data/mapped/30/mapped_heart_left_ventricle_30.csv
./data/mapped/30/mapped_adipose_subcutaneous_30.csv
./data/mapped/30/mapped_breast_mammary_tissue_30.csv
./data/mapped/30/mapped_skin_not_sun_exposed_suprapubic_30.csv
./data/mapped/30/mapped_brain_substantia_nigra_30.csv
./data/mapped/30/mapped_adipose_visceral_omentum_30.csv
./data/mapped/30/mapped_brain_amygdala_30.csv
./data/mapped/30/mapped_brain_cortex_30.csv
./data/mapped/30/mapped_pituitary_30.csv
./data/mapped/30/mapped_small_intestine_terminal_ileum_30.csv
./data/mapped/30/mapped_cells_cultured_fibroblasts_30.csv
./data/mapped/30/mapped_vagina_30.csv
./data/mapped/30/mapped_muscle_skeletal_30.csv
./data/mapped/30/mapped_prostate_30.csv
./data/mapped/30/mapped_brain_cerebellar_hemisphere_30.csv
./data/mapped/30/mapped_colon_sigmoid_30.csv
./data/mapped/30/mapped_esophagus_mucosa_30.csv
./data/mapped/30/mapped_artery_aorta_30.csv
./data/mapped/50/mapped_muscle_skeletal_50.csv
./data/mapped/50/mapped_spleen_50.csv
./data/mapped/50/mapped_adipose_subcutaneous_50.csv
./data/mapped/50/mapped_small_intestine_terminal_ileum_50.csv
./data/mapped/50/mapped_esophagus_gastroesophageal_junction_50.csv
./data/mapped/50/mapped_brain_spinal_cord_cervical_c-1)_50.csv
./data/mapped/50/mapped_esophagus_mucosa_50.csv
./data/mapped/50/mapped_prostate_50.csv
./data/mapped/50/mapped_whole_blood_50.csv
./data/mapped/50/mapped_thyroid_50.csv
./data/mapped/50/mapped_vagina_50.csv
./data/mapped/50/mapped_brain_putamen_basal_ganglia_50.csv
./data/mapped/50/mapped_brain_frontal_cortex_ba9_50.csv
./data/mapped/50/mapped_liver_50.csv
./data/mapped/50/mapped_cells_cultured_fibroblasts_50.csv
./data/mapped/50/mapped_brain_hypothalamus_50.csv
./data/mapped/50/mapped_uterus_50.csv
./data/mapped/50/mapped_brain_amygdala_50.csv
./data/mapped/50/mapped_colon_sigmoid_50.csv
./data/mapped/50/mapped_nerve_tibial_50.csv
./data/mapped/50/mapped_brain_hippocampus_50.csv
./data/mapped/50/mapped_artery_tibial_50.csv
./data/mapped/50/mapped_cells_ebv-transformed_lymphocytes_50.csv
./data/mapped/50/mapped_adipose_visceral_omentum_50.csv
./data/mapped/50/mapped_heart_left_ventricle_50.csv
./data/mapped/50/mapped_brain_substantia_nigra_50.csv
./data/mapped/50/mapped_testis_50.csv
./data/mapped/50/mapped_artery_aorta_50.csv
./data/mapped/50/mapped_breast_mammary_tissue_50.csv
./data/mapped/50/mapped_pituitary_50.csv
./data/mapped/50/mapped_skin_sun_exposed_lower_leg_50.csv
./data/mapped/50/mapped_artery_coronary_50.csv
./data/mapped/50/mapped_minor_salivary_gland_50.csv
./data/mapped/50/mapped_ovary_50.csv
./data/mapped/50/mapped_colon_transverse_50.csv
./data/mapped/50/mapped_skin_not_sun_exposed_suprapubic_50.csv
./data/mapped/50/mapped_adrenal_gland_50.csv
./data/mapped/50/mapped_pancreas_50.csv
./data/mapped/50/mapped_lung_50.csv
./data/mapped/50/mapped_stomach_50.csv
./data/mapped/50/mapped_brain_caudate_basal_ganglia_50.csv
./data/mapped/50/mapped_brain_anterior_cingulate_cortex_ba24_50.csv
./data/mapped/50/mapped_esophagus_muscularis_50.csv
./data/mapped/50/mapped_heart_atrial_appendage_50.csv
./data/mapped/50/mapped_brain_cerebellum_50.csv
./data/mapped/50/mapped_brain_cerebellar_hemisphere_50.csv
./data/mapped/50/mapped_brain_nucleus_accumbens_basal ganglia_50.csv
./data/mapped/50/mapped_brain_cortex_50.csv
./data/mapped/60/mapped_brain_spinal_cord_cervical_c-1)_60.csv
./data/mapped/60/mapped_whole_blood_60.csv
./data/mapped/60/mapped_brain_substantia_nigra_60.csv
./data/mapped/60/mapped_lung_60.csv
./data/mapped/60/mapped_artery_coronary_60.csv
./data/mapped/60/mapped_stomach_60.csv
./data/mapped/60/mapped_uterus_60.csv
./data/mapped/60/mapped_brain_cerebellum_60.csv
./data/mapped/60/mapped_brain_cerebellar_hemisphere_60.csv
./data/mapped/60/mapped_skin_not_sun_exposed_suprapubic_60.csv
./data/mapped/60/mapped_adipose_visceral_omentum_60.csv
./data/mapped/60/mapped_spleen_60.csv
./data/mapped/60/mapped_testis_60.csv
./data/mapped/60/mapped_artery_tibial_60.csv
./data/mapped/60/mapped_brain_hypothalamus_60.csv
./data/mapped/60/mapped_esophagus_muscularis_60.csv
./data/mapped/60/mapped_brain_nucleus_accumbens_basal ganglia_60.csv
./data/mapped/60/mapped_heart_atrial_appendage_60.csv
./data/mapped/60/mapped_brain_caudate_basal_ganglia_60.csv
./data/mapped/60/mapped_brain_hippocampus_60.csv
./data/mapped/60/mapped_colon_sigmoid_60.csv
./data/mapped/60/mapped_brain_cortex_60.csv
./data/mapped/60/mapped_brain_anterior_cingulate_cortex_ba24_60.csv
./data/mapped/60/mapped_pituitary_60.csv
./data/mapped/60/mapped_artery_aorta_60.csv
./data/mapped/60/mapped_muscle_skeletal_60.csv
./data/mapped/60/mapped_breast_mammary_tissue_60.csv
./data/mapped/60/mapped_brain_putamen_basal_ganglia_60.csv
./data/mapped/60/mapped_cells_ebv-transformed_lymphocytes_60.csv
./data/mapped/60/mapped_esophagus_mucosa_60.csv
./data/mapped/60/mapped_minor_salivary_gland_60.csv
./data/mapped/60/mapped_adrenal_gland_60.csv
./data/mapped/60/mapped_cells_cultured_fibroblasts_60.csv
./data/mapped/60/mapped_liver_60.csv
./data/mapped/60/mapped_nerve_tibial_60.csv
./data/mapped/60/mapped_thyroid_60.csv
./data/mapped/60/mapped_adipose_subcutaneous_60.csv
./data/mapped/60/mapped_vagina_60.csv
./data/mapped/60/mapped_heart_left_ventricle_60.csv
./data/mapped/60/mapped_pancreas_60.csv
./data/mapped/60/mapped_prostate_60.csv
./data/mapped/60/mapped_brain_amygdala_60.csv
./data/mapped/60/mapped_brain_frontal_cortex_ba9_60.csv
./data/mapped/60/mapped_colon_transverse_60.csv
./data/mapped/60/mapped_skin_sun_exposed_lower_leg_60.csv
./data/mapped/60/mapped_ovary_60.csv
./data/mapped/60/mapped_small_intestine_terminal_ileum_60.csv
./data/mapped/60/mapped_esophagus_gastroesophageal_junction_60.csv
./data/mapped/70/mapped_heart_left_ventricle_70.csv
./data/mapped/70/mapped_artery_aorta_70.csv
./data/mapped/70/mapped_thyroid_70.csv
./data/mapped/70/mapped_nerve_tibial_70.csv
./data/mapped/70/mapped_colon_transverse_70.csv
./data/mapped/70/mapped_pituitary_70.csv
./data/mapped/70/mapped_brain_hippocampus_70.csv
./data/mapped/70/mapped_artery_coronary_70.csv
./data/mapped/70/mapped_brain_hypothalamus_70.csv
./data/mapped/70/mapped_brain_substantia_nigra_70.csv
./data/mapped/70/mapped_vagina_70.csv
./data/mapped/70/mapped_esophagus_gastroesophageal_junction_70.csv
./data/mapped/70/mapped_breast_mammary_tissue_70.csv
./data/mapped/70/mapped_brain_spinal_cord_cervical_c-1)_70.csv
./data/mapped/70/mapped_testis_70.csv
./data/mapped/70/mapped_adipose_subcutaneous_70.csv
./data/mapped/70/mapped_adrenal_gland_70.csv
./data/mapped/70/mapped_brain_frontal_cortex_ba9_70.csv
./data/mapped/70/mapped_uterus_70.csv
./data/mapped/70/mapped_brain_anterior_cingulate_cortex_ba24_70.csv
./data/mapped/70/mapped_esophagus_mucosa_70.csv
./data/mapped/70/mapped_prostate_70.csv
./data/mapped/70/mapped_artery_tibial_70.csv
./data/mapped/70/mapped_brain_nucleus_accumbens_basal ganglia_70.csv
./data/mapped/70/mapped_brain_putamen_basal_ganglia_70.csv
./data/mapped/70/mapped_stomach_70.csv
./data/mapped/70/mapped_skin_sun_exposed_lower_leg_70.csv
./data/mapped/70/mapped_pancreas_70.csv
./data/mapped/70/mapped_skin_not_sun_exposed_suprapubic_70.csv
./data/mapped/70/mapped_small_intestine_terminal_ileum_70.csv
./data/mapped/70/mapped_brain_caudate_basal_ganglia_70.csv
./data/mapped/70/mapped_colon_sigmoid_70.csv
./data/mapped/70/mapped_muscle_skeletal_70.csv
./data/mapped/70/mapped_adipose_visceral_omentum_70.csv
./data/mapped/70/mapped_lung_70.csv
./data/mapped/70/mapped_spleen_70.csv
./data/mapped/70/mapped_brain_amygdala_70.csv
./data/mapped/70/mapped_cells_ebv-transformed_lymphocytes_70.csv
./data/mapped/70/mapped_brain_cerebellum_70.csv
./data/mapped/70/mapped_liver_70.csv
./data/mapped/70/mapped_brain_cerebellar_hemisphere_70.csv
./data/mapped/70/mapped_heart_atrial_appendage_70.csv
./data/mapped/70/mapped_brain_cortex_70.csv
./data/mapped/70/mapped_cells_cultured_fibroblasts_70.csv
./data/mapped/70/mapped_whole_blood_70.csv
./data/mapped/70/mapped_esophagus_muscularis_70.csv
./data/mapped/70/mapped_ovary_70.csv
./data/mapped/70/mapped_minor_salivary_gland_70.csv
./data/mapped/20/mapped_brain_cortex_20.csv
./data/mapped/20/mapped_whole_blood_20.csv
./data/mapped/20/mapped_esophagus_muscularis_20.csv
./data/mapped/20/mapped_artery_coronary_20.csv
./data/mapped/20/mapped_small_intestine_terminal_ileum_20.csv
./data/mapped/20/mapped_breast_mammary_tissue_20.csv
./data/mapped/20/mapped_lung_20.csv
./data/mapped/20/mapped_brain_cerebellar_hemisphere_20.csv
./data/mapped/20/mapped_brain_hippocampus_20.csv
./data/mapped/20/mapped_adipose_visceral_omentum_20.csv
./data/mapped/20/mapped_minor_salivary_gland_20.csv
./data/mapped/20/mapped_colon_sigmoid_20.csv
./data/mapped/20/mapped_skin_sun_exposed_lower_leg_20.csv
./data/mapped/20/mapped_cells_cultured_fibroblasts_20.csv
./data/mapped/20/mapped_cells_ebv-transformed_lymphocytes_20.csv
./data/mapped/20/mapped_adrenal_gland_20.csv
./data/mapped/20/mapped_brain_caudate_basal_ganglia_20.csv
./data/mapped/20/mapped_prostate_20.csv
./data/mapped/20/mapped_brain_frontal_cortex_ba9_20.csv
./data/mapped/20/mapped_uterus_20.csv
./data/mapped/20/mapped_esophagus_gastroesophageal_junction_20.csv
./data/mapped/20/mapped_pituitary_20.csv
./data/mapped/20/mapped_ovary_20.csv
./data/mapped/20/mapped_artery_aorta_20.csv
./data/mapped/20/mapped_muscle_skeletal_20.csv
./data/mapped/20/mapped_brain_spinal_cord_cervical_c-1)_20.csv
./data/mapped/20/mapped_brain_hypothalamus_20.csv
./data/mapped/20/mapped_nerve_tibial_20.csv
./data/mapped/20/mapped_brain_amygdala_20.csv
./data/mapped/20/mapped_adipose_subcutaneous_20.csv
./data/mapped/20/mapped_stomach_20.csv
./data/mapped/20/mapped_heart_atrial_appendage_20.csv
./data/mapped/20/mapped_colon_transverse_20.csv
./data/mapped/20/mapped_spleen_20.csv
./data/mapped/20/mapped_pancreas_20.csv
./data/mapped/20/mapped_thyroid_20.csv
./data/mapped/20/mapped_artery_tibial_20.csv
./data/mapped/20/mapped_brain_anterior_cingulate_cortex_ba24_20.csv
./data/mapped/20/mapped_brain_substantia_nigra_20.csv
./data/mapped/20/mapped_skin_not_sun_exposed_suprapubic_20.csv
./data/mapped/20/mapped_brain_cerebellum_20.csv
./data/mapped/20/mapped_brain_nucleus_accumbens_basal ganglia_20.csv
./data/mapped/20/mapped_vagina_20.csv
./data/mapped/20/mapped_testis_20.csv
./data/mapped/20/mapped_heart_left_ventricle_20.csv
./data/mapped/20/mapped_liver_20.csv
./data/mapped/20/mapped_brain_putamen_basal_ganglia_20.csv
./data/mapped/20/mapped_esophagus_mucosa_20.csv
./data/mapped/40/mapped_vagina_40.csv
./data/mapped/40/mapped_skin_not_sun_exposed_suprapubic_40.csv
./data/mapped/40/mapped_ovary_40.csv
./data/mapped/40/mapped_esophagus_gastroesophageal_junction_40.csv
./data/mapped/40/mapped_brain_putamen_basal_ganglia_40.csv
./data/mapped/40/mapped_adrenal_gland_40.csv
./data/mapped/40/mapped_brain_hypothalamus_40.csv
./data/mapped/40/mapped_esophagus_muscularis_40.csv
./data/mapped/40/mapped_brain_substantia_nigra_40.csv
./data/mapped/40/mapped_prostate_40.csv
./data/mapped/40/mapped_stomach_40.csv
./data/mapped/40/mapped_small_intestine_terminal_ileum_40.csv
./data/mapped/40/mapped_muscle_skeletal_40.csv
./data/mapped/40/mapped_liver_40.csv
./data/mapped/40/mapped_brain_cerebellum_40.csv
./data/mapped/40/mapped_spleen_40.csv
./data/mapped/40/mapped_nerve_tibial_40.csv
./data/mapped/40/mapped_lung_40.csv
./data/mapped/40/mapped_brain_hippocampus_40.csv
./data/mapped/40/mapped_brain_spinal_cord_cervical_c-1)_40.csv
./data/mapped/40/mapped_brain_anterior_cingulate_cortex_ba24_40.csv
./data/mapped/40/mapped_cells_cultured_fibroblasts_40.csv
./data/mapped/40/mapped_testis_40.csv
./data/mapped/40/mapped_brain_cerebellar_hemisphere_40.csv
./data/mapped/40/mapped_minor_salivary_gland_40.csv
./data/mapped/40/mapped_brain_cortex_40.csv
./data/mapped/40/mapped_colon_transverse_40.csv
./data/mapped/40/mapped_skin_sun_exposed_lower_leg_40.csv
./data/mapped/40/mapped_brain_caudate_basal_ganglia_40.csv
./data/mapped/40/mapped_pituitary_40.csv
./data/mapped/40/mapped_heart_left_ventricle_40.csv
./data/mapped/40/mapped_brain_amygdala_40.csv
./data/mapped/40/mapped_artery_aorta_40.csv
./data/mapped/40/mapped_heart_atrial_appendage_40.csv
./data/mapped/40/mapped_colon_sigmoid_40.csv
./data/mapped/40/mapped_brain_frontal_cortex_ba9_40.csv
./data/mapped/40/mapped_thyroid_40.csv
./data/mapped/40/mapped_uterus_40.csv
./data/mapped/40/mapped_cells_ebv-transformed_lymphocytes_40.csv
./data/mapped/40/mapped_esophagus_mucosa_40.csv
./data/mapped/40/mapped_breast_mammary_tissue_40.csv
./data/mapped/40/mapped_artery_coronary_40.csv
./data/mapped/40/mapped_whole_blood_40.csv
./data/mapped/40/mapped_adipose_visceral_omentum_40.csv
./data/mapped/40/mapped_artery_tibial_40.csv
./data/mapped/40/mapped_pancreas_40.csv
./data/mapped/40/mapped_adipose_subcutaneous_40.csv
./data/mapped/40/mapped_brain_nucleus_accumbens_basal ganglia_40.csv

In [30]:
%%R

library(dplyr)

disease_gene <- read.csv("data/bpco_gene_disease_associations.csv",
                         stringsAsFactors = FALSE)

drug_gene <- read.csv("data/bpco_drug_gene_associations.csv",
                      stringsAsFactors = FALSE)

disease_gene$geneSymbol <- toupper(trimws(disease_gene$geneSymbol))
drug_gene$gene_name <- toupper(trimws(drug_gene$gene_name))

bpco_genes <- unique(na.omit(disease_gene$geneSymbol))

drug_gene_filtered <- drug_gene %>%
  filter(gene_name %in% bpco_genes) %>%
  select(drug_name, gene_name) %>%
  distinct()

cat("BPCO disease-gene rows:", nrow(disease_gene), "\n")
cat("Unique BPCO disease genes:", length(bpco_genes), "\n")
cat("Filtered BPCO drug-gene rows:", nrow(drug_gene_filtered), "\n")
cat("Unique BPCO drugs:", length(unique(drug_gene_filtered$drug_name)), "\n")

write.csv(disease_gene,
          "data/bpco_disease_genes_clean.csv",
          row.names = FALSE)

write.csv(drug_gene_filtered,
          "data/bpco_drug_gene_filtered_clean.csv",
          row.names = FALSE)

BPCO disease-gene rows: 261
Unique BPCO disease genes: 209
Filtered BPCO drug-gene rows: 5448
Unique BPCO drugs: 3657

In [31]:
!find . -type f | grep -Ei "gtex|trrust|expression|network|gene|drug|efficacy|rds|csv|tsv|R$|py$"

./src/final_visuals.R
./src/gene_networks.R
./src/drug_efficacy.R
./src/normalize_all_tissues.R
./src/normalize_tissue.R
./src/algorithm_0.R
./src/null_algorithm.R
./src/algorithm_1.R
./src/utility.R
./src/drug_efficacy_bpco.R
./src/age_indexing/webscrape.py
./src/age_indexing/compare_algorithms.py
./src/age_indexing/create_visuals.py
./src/age_indexing/z_score_visuals.py
./src/age_based_influence.R
./data/normalized/normalized_artery_coronary.csv
./data/normalized/normalized_brain_anterior_cingulate_cortex_ba24.csv
./data/normalized/normalized_thyroid.csv
./data/normalized/normalized_vagina.csv
./data/normalized/normalized_breast_mammary_tissue.csv
./data/normalized/normalized_uterus.csv
./data/normalized/normalized_brain_putamen_basal_ganglia.csv
./data/normalized/normalized_cells_ebv-transformed_lymphocytes.csv
./data/normalized/normalized_colon_transverse.csv
./data/normalized/normalized_heart_left_ventricle.csv
./data/normalized/normalized_colon_sigmoid.csv
./data/normalized/normalized_brain_caudate_basal_ganglia.csv
./data/normalized/normalized_brain_substantia_nigra.csv
./data/normalized/normalized_pancreas.csv
./data/normalized/normalized_spleen.csv
./data/normalized/normalized_stomach.csv
./data/normalized/normalized_heart_atrial_appendage.csv
./data/normalized/normalized_adrenal_gland.csv
./data/normalized/normalized_brain_hippocampus.csv
./data/normalized/normalized_brain_spinal_cord_cervical_c-1).csv
./data/normalized/normalized_prostate.csv
./data/normalized/normalized_brain_cortex.csv
./data/normalized/normalized_adipose_visceral_omentum.csv
./data/normalized/normalized_brain_amygdala.csv
./data/normalized/normalized_brain_cerebellar_hemisphere.csv
./data/normalized/normalized_esophagus_gastroesophageal_junction.csv
./data/normalized/normalized_adipose_subcutaneous.csv
./data/normalized/normalized_testis.csv
./data/normalized/normalized_minor_salivary_gland.csv
./data/normalized/normalized_brain_frontal_cortex_ba9.csv
./data/normalized/normalized_skin_not_sun_exposed_suprapubic.csv
./data/normalized/normalized_brain_nucleus_accumbens_basal ganglia.csv
./data/normalized/normalized_brain_cerebellum.csv
./data/normalized/normalized_nerve_tibial.csv
./data/normalized/normalized_muscle_skeletal.csv
./data/normalized/normalized_lung.csv
./data/normalized/normalized_brain_hypothalamus.csv
./data/normalized/normalized_skin_sun_exposed_lower_leg.csv
./data/normalized/normalized_small_intestine_terminal_ileum.csv
./data/normalized/normalized_liver.csv
./data/normalized/normalized_ovary.csv
./data/normalized/normalized_cells_cultured_fibroblasts.csv
./data/normalized/normalized_kidney_cortex.csv
./data/normalized/normalized_pituitary.csv
./data/normalized/normalized_whole_blood.csv
./data/normalized/normalized_esophagus_mucosa.csv
./data/normalized/normalized_artery_aorta.csv
./data/normalized/normalized_esophagus_muscularis.csv
./data/normalized/normalized_artery_tibial.csv
./data/bpco_drug_gene_filtered_clean.csv
./data/bpco_drug_gene_associations.csv
./data/bpco_disease_genes_clean.csv
./data/bpco_gene_disease_associations.csv
./data/age_indexes/pubmed_genes.xlsx
./data/age_indexes/excel_files/pubmed_genes.xlsx
./data/drug/filtered_drug_gene_dataset.xlsx
./data/drug/filtered_neurodegenerative_diseases.csv
./data/drug/efficacy-alzheimers.csv
./data/drug/efficacy-multiple sclerosis.csv
./data/drug/efficacy-parkinson.csv
./data/drug/filtered_drug_gene_dataset.csv
./data/mapped/30/mapped_artery_tibial_30.csv
./data/mapped/30/mapped_liver_30.csv
./data/mapped/30/mapped_nerve_tibial_30.csv
./data/mapped/30/mapped_colon_transverse_30.csv
./data/mapped/30/mapped_adrenal_gland_30.csv
./data/mapped/30/mapped_brain_nucleus_accumbens_basal ganglia_30.csv
./data/mapped/30/mapped_heart_atrial_appendage_30.csv
./data/mapped/30/mapped_brain_hypothalamus_30.csv
./data/mapped/30/mapped_whole_blood_30.csv
./data/mapped/30/mapped_brain_anterior_cingulate_cortex_ba24_30.csv
./data/mapped/30/mapped_brain_cerebellum_30.csv
./data/mapped/30/mapped_esophagus_muscularis_30.csv
./data/mapped/30/mapped_ovary_30.csv
./data/mapped/30/mapped_lung_30.csv
./data/mapped/30/mapped_testis_30.csv
./data/mapped/30/mapped_brain_putamen_basal_ganglia_30.csv
./data/mapped/30/mapped_uterus_30.csv
./data/mapped/30/mapped_artery_coronary_30.csv
./data/mapped/30/mapped_minor_salivary_gland_30.csv
./data/mapped/30/mapped_spleen_30.csv
./data/mapped/30/mapped_stomach_30.csv
./data/mapped/30/mapped_thyroid_30.csv
./data/mapped/30/mapped_pancreas_30.csv
./data/mapped/30/mapped_cells_ebv-transformed_lymphocytes_30.csv
./data/mapped/30/mapped_esophagus_gastroesophageal_junction_30.csv
./data/mapped/30/mapped_skin_sun_exposed_lower_leg_30.csv
./data/mapped/30/mapped_brain_spinal_cord_cervical_c-1)_30.csv
./data/mapped/30/mapped_brain_caudate_basal_ganglia_30.csv
./data/mapped/30/mapped_brain_frontal_cortex_ba9_30.csv
./data/mapped/30/mapped_brain_hippocampus_30.csv
./data/mapped/30/mapped_heart_left_ventricle_30.csv
./data/mapped/30/mapped_adipose_subcutaneous_30.csv
./data/mapped/30/mapped_breast_mammary_tissue_30.csv
./data/mapped/30/mapped_skin_not_sun_exposed_suprapubic_30.csv
./data/mapped/30/mapped_brain_substantia_nigra_30.csv
./data/mapped/30/mapped_adipose_visceral_omentum_30.csv
./data/mapped/30/mapped_brain_amygdala_30.csv
./data/mapped/30/mapped_brain_cortex_30.csv
./data/mapped/30/mapped_pituitary_30.csv
./data/mapped/30/mapped_small_intestine_terminal_ileum_30.csv
./data/mapped/30/mapped_cells_cultured_fibroblasts_30.csv
./data/mapped/30/mapped_vagina_30.csv
./data/mapped/30/mapped_muscle_skeletal_30.csv
./data/mapped/30/mapped_prostate_30.csv
./data/mapped/30/mapped_brain_cerebellar_hemisphere_30.csv
./data/mapped/30/mapped_colon_sigmoid_30.csv
./data/mapped/30/mapped_esophagus_mucosa_30.csv
./data/mapped/30/mapped_artery_aorta_30.csv
./data/mapped/50/mapped_muscle_skeletal_50.csv
./data/mapped/50/mapped_spleen_50.csv
./data/mapped/50/mapped_adipose_subcutaneous_50.csv
./data/mapped/50/mapped_small_intestine_terminal_ileum_50.csv
./data/mapped/50/mapped_esophagus_gastroesophageal_junction_50.csv
./data/mapped/50/mapped_brain_spinal_cord_cervical_c-1)_50.csv
./data/mapped/50/mapped_esophagus_mucosa_50.csv
./data/mapped/50/mapped_prostate_50.csv
./data/mapped/50/mapped_whole_blood_50.csv
./data/mapped/50/mapped_thyroid_50.csv
./data/mapped/50/mapped_vagina_50.csv
./data/mapped/50/mapped_brain_putamen_basal_ganglia_50.csv
./data/mapped/50/mapped_brain_frontal_cortex_ba9_50.csv
./data/mapped/50/mapped_liver_50.csv
./data/mapped/50/mapped_cells_cultured_fibroblasts_50.csv
./data/mapped/50/mapped_brain_hypothalamus_50.csv
./data/mapped/50/mapped_uterus_50.csv
./data/mapped/50/mapped_brain_amygdala_50.csv
./data/mapped/50/mapped_colon_sigmoid_50.csv
./data/mapped/50/mapped_nerve_tibial_50.csv
./data/mapped/50/mapped_brain_hippocampus_50.csv
./data/mapped/50/mapped_artery_tibial_50.csv
./data/mapped/50/mapped_cells_ebv-transformed_lymphocytes_50.csv
./data/mapped/50/mapped_adipose_visceral_omentum_50.csv
./data/mapped/50/mapped_heart_left_ventricle_50.csv
./data/mapped/50/mapped_brain_substantia_nigra_50.csv
./data/mapped/50/mapped_testis_50.csv
./data/mapped/50/mapped_artery_aorta_50.csv
./data/mapped/50/mapped_breast_mammary_tissue_50.csv
./data/mapped/50/mapped_pituitary_50.csv
./data/mapped/50/mapped_skin_sun_exposed_lower_leg_50.csv
./data/mapped/50/mapped_artery_coronary_50.csv
./data/mapped/50/mapped_minor_salivary_gland_50.csv
./data/mapped/50/mapped_ovary_50.csv
./data/mapped/50/mapped_colon_transverse_50.csv
./data/mapped/50/mapped_skin_not_sun_exposed_suprapubic_50.csv
./data/mapped/50/mapped_adrenal_gland_50.csv
./data/mapped/50/mapped_pancreas_50.csv
./data/mapped/50/mapped_lung_50.csv
./data/mapped/50/mapped_stomach_50.csv
./data/mapped/50/mapped_brain_caudate_basal_ganglia_50.csv
./data/mapped/50/mapped_brain_anterior_cingulate_cortex_ba24_50.csv
./data/mapped/50/mapped_esophagus_muscularis_50.csv
./data/mapped/50/mapped_heart_atrial_appendage_50.csv
./data/mapped/50/mapped_brain_cerebellum_50.csv
./data/mapped/50/mapped_brain_cerebellar_hemisphere_50.csv
./data/mapped/50/mapped_brain_nucleus_accumbens_basal ganglia_50.csv
./data/mapped/50/mapped_brain_cortex_50.csv
./data/mapped/60/mapped_brain_spinal_cord_cervical_c-1)_60.csv
./data/mapped/60/mapped_whole_blood_60.csv
./data/mapped/60/mapped_brain_substantia_nigra_60.csv
./data/mapped/60/mapped_lung_60.csv
./data/mapped/60/mapped_artery_coronary_60.csv
./data/mapped/60/mapped_stomach_60.csv
./data/mapped/60/mapped_uterus_60.csv
./data/mapped/60/mapped_brain_cerebellum_60.csv
./data/mapped/60/mapped_brain_cerebellar_hemisphere_60.csv
./data/mapped/60/mapped_skin_not_sun_exposed_suprapubic_60.csv
./data/mapped/60/mapped_adipose_visceral_omentum_60.csv
./data/mapped/60/mapped_spleen_60.csv
./data/mapped/60/mapped_testis_60.csv
./data/mapped/60/mapped_artery_tibial_60.csv
./data/mapped/60/mapped_brain_hypothalamus_60.csv
./data/mapped/60/mapped_esophagus_muscularis_60.csv
./data/mapped/60/mapped_brain_nucleus_accumbens_basal ganglia_60.csv
./data/mapped/60/mapped_heart_atrial_appendage_60.csv
./data/mapped/60/mapped_brain_caudate_basal_ganglia_60.csv
./data/mapped/60/mapped_brain_hippocampus_60.csv
./data/mapped/60/mapped_colon_sigmoid_60.csv
./data/mapped/60/mapped_brain_cortex_60.csv
./data/mapped/60/mapped_brain_anterior_cingulate_cortex_ba24_60.csv
./data/mapped/60/mapped_pituitary_60.csv
./data/mapped/60/mapped_artery_aorta_60.csv
./data/mapped/60/mapped_muscle_skeletal_60.csv
./data/mapped/60/mapped_breast_mammary_tissue_60.csv
./data/mapped/60/mapped_brain_putamen_basal_ganglia_60.csv
./data/mapped/60/mapped_cells_ebv-transformed_lymphocytes_60.csv
./data/mapped/60/mapped_esophagus_mucosa_60.csv
./data/mapped/60/mapped_minor_salivary_gland_60.csv
./data/mapped/60/mapped_adrenal_gland_60.csv
./data/mapped/60/mapped_cells_cultured_fibroblasts_60.csv
./data/mapped/60/mapped_liver_60.csv
./data/mapped/60/mapped_nerve_tibial_60.csv
./data/mapped/60/mapped_thyroid_60.csv
./data/mapped/60/mapped_adipose_subcutaneous_60.csv
./data/mapped/60/mapped_vagina_60.csv
./data/mapped/60/mapped_heart_left_ventricle_60.csv
./data/mapped/60/mapped_pancreas_60.csv
./data/mapped/60/mapped_prostate_60.csv
./data/mapped/60/mapped_brain_amygdala_60.csv
./data/mapped/60/mapped_brain_frontal_cortex_ba9_60.csv
./data/mapped/60/mapped_colon_transverse_60.csv
./data/mapped/60/mapped_skin_sun_exposed_lower_leg_60.csv
./data/mapped/60/mapped_ovary_60.csv
./data/mapped/60/mapped_small_intestine_terminal_ileum_60.csv
./data/mapped/60/mapped_esophagus_gastroesophageal_junction_60.csv
./data/mapped/70/mapped_heart_left_ventricle_70.csv
./data/mapped/70/mapped_artery_aorta_70.csv
./data/mapped/70/mapped_thyroid_70.csv
./data/mapped/70/mapped_nerve_tibial_70.csv
./data/mapped/70/mapped_colon_transverse_70.csv
./data/mapped/70/mapped_pituitary_70.csv
./data/mapped/70/mapped_brain_hippocampus_70.csv
./data/mapped/70/mapped_artery_coronary_70.csv
./data/mapped/70/mapped_brain_hypothalamus_70.csv
./data/mapped/70/mapped_brain_substantia_nigra_70.csv
./data/mapped/70/mapped_vagina_70.csv
./data/mapped/70/mapped_esophagus_gastroesophageal_junction_70.csv
./data/mapped/70/mapped_breast_mammary_tissue_70.csv
./data/mapped/70/mapped_brain_spinal_cord_cervical_c-1)_70.csv
./data/mapped/70/mapped_testis_70.csv
./data/mapped/70/mapped_adipose_subcutaneous_70.csv
./data/mapped/70/mapped_adrenal_gland_70.csv
./data/mapped/70/mapped_brain_frontal_cortex_ba9_70.csv
./data/mapped/70/mapped_uterus_70.csv
./data/mapped/70/mapped_brain_anterior_cingulate_cortex_ba24_70.csv
./data/mapped/70/mapped_esophagus_mucosa_70.csv
./data/mapped/70/mapped_prostate_70.csv
./data/mapped/70/mapped_artery_tibial_70.csv
./data/mapped/70/mapped_brain_nucleus_accumbens_basal ganglia_70.csv
./data/mapped/70/mapped_brain_putamen_basal_ganglia_70.csv
./data/mapped/70/mapped_stomach_70.csv
./data/mapped/70/mapped_skin_sun_exposed_lower_leg_70.csv
./data/mapped/70/mapped_pancreas_70.csv
./data/mapped/70/mapped_skin_not_sun_exposed_suprapubic_70.csv
./data/mapped/70/mapped_small_intestine_terminal_ileum_70.csv
./data/mapped/70/mapped_brain_caudate_basal_ganglia_70.csv
./data/mapped/70/mapped_colon_sigmoid_70.csv
./data/mapped/70/mapped_muscle_skeletal_70.csv
./data/mapped/70/mapped_adipose_visceral_omentum_70.csv
./data/mapped/70/mapped_lung_70.csv
./data/mapped/70/mapped_spleen_70.csv
./data/mapped/70/mapped_brain_amygdala_70.csv
./data/mapped/70/mapped_cells_ebv-transformed_lymphocytes_70.csv
./data/mapped/70/mapped_brain_cerebellum_70.csv
./data/mapped/70/mapped_liver_70.csv
./data/mapped/70/mapped_brain_cerebellar_hemisphere_70.csv
./data/mapped/70/mapped_heart_atrial_appendage_70.csv
./data/mapped/70/mapped_brain_cortex_70.csv
./data/mapped/70/mapped_cells_cultured_fibroblasts_70.csv
./data/mapped/70/mapped_whole_blood_70.csv
./data/mapped/70/mapped_esophagus_muscularis_70.csv
./data/mapped/70/mapped_ovary_70.csv
./data/mapped/70/mapped_minor_salivary_gland_70.csv
./data/mapped/20/mapped_brain_cortex_20.csv
./data/mapped/20/mapped_whole_blood_20.csv
./data/mapped/20/mapped_esophagus_muscularis_20.csv
./data/mapped/20/mapped_artery_coronary_20.csv
./data/mapped/20/mapped_small_intestine_terminal_ileum_20.csv
./data/mapped/20/mapped_breast_mammary_tissue_20.csv
./data/mapped/20/mapped_lung_20.csv
./data/mapped/20/mapped_brain_cerebellar_hemisphere_20.csv
./data/mapped/20/mapped_brain_hippocampus_20.csv
./data/mapped/20/mapped_adipose_visceral_omentum_20.csv
./data/mapped/20/mapped_minor_salivary_gland_20.csv
./data/mapped/20/mapped_colon_sigmoid_20.csv
./data/mapped/20/mapped_skin_sun_exposed_lower_leg_20.csv
./data/mapped/20/mapped_cells_cultured_fibroblasts_20.csv
./data/mapped/20/mapped_cells_ebv-transformed_lymphocytes_20.csv
./data/mapped/20/mapped_adrenal_gland_20.csv
./data/mapped/20/mapped_brain_caudate_basal_ganglia_20.csv
./data/mapped/20/mapped_prostate_20.csv
./data/mapped/20/mapped_brain_frontal_cortex_ba9_20.csv
./data/mapped/20/mapped_uterus_20.csv
./data/mapped/20/mapped_esophagus_gastroesophageal_junction_20.csv
./data/mapped/20/mapped_pituitary_20.csv
./data/mapped/20/mapped_ovary_20.csv
./data/mapped/20/mapped_artery_aorta_20.csv
./data/mapped/20/mapped_muscle_skeletal_20.csv
./data/mapped/20/mapped_brain_spinal_cord_cervical_c-1)_20.csv
./data/mapped/20/mapped_brain_hypothalamus_20.csv
./data/mapped/20/mapped_nerve_tibial_20.csv
./data/mapped/20/mapped_brain_amygdala_20.csv
./data/mapped/20/mapped_adipose_subcutaneous_20.csv
./data/mapped/20/mapped_stomach_20.csv
./data/mapped/20/mapped_heart_atrial_appendage_20.csv
./data/mapped/20/mapped_colon_transverse_20.csv
./data/mapped/20/mapped_spleen_20.csv
./data/mapped/20/mapped_pancreas_20.csv
./data/mapped/20/mapped_thyroid_20.csv
./data/mapped/20/mapped_artery_tibial_20.csv
./data/mapped/20/mapped_brain_anterior_cingulate_cortex_ba24_20.csv
./data/mapped/20/mapped_brain_substantia_nigra_20.csv
./data/mapped/20/mapped_skin_not_sun_exposed_suprapubic_20.csv
./data/mapped/20/mapped_brain_cerebellum_20.csv
./data/mapped/20/mapped_brain_nucleus_accumbens_basal ganglia_20.csv
./data/mapped/20/mapped_vagina_20.csv
./data/mapped/20/mapped_testis_20.csv
./data/mapped/20/mapped_heart_left_ventricle_20.csv
./data/mapped/20/mapped_liver_20.csv
./data/mapped/20/mapped_brain_putamen_basal_ganglia_20.csv
./data/mapped/20/mapped_esophagus_mucosa_20.csv
./data/mapped/40/mapped_vagina_40.csv
./data/mapped/40/mapped_skin_not_sun_exposed_suprapubic_40.csv
./data/mapped/40/mapped_ovary_40.csv
./data/mapped/40/mapped_esophagus_gastroesophageal_junction_40.csv
./data/mapped/40/mapped_brain_putamen_basal_ganglia_40.csv
./data/mapped/40/mapped_adrenal_gland_40.csv
./data/mapped/40/mapped_brain_hypothalamus_40.csv
./data/mapped/40/mapped_esophagus_muscularis_40.csv
./data/mapped/40/mapped_brain_substantia_nigra_40.csv
./data/mapped/40/mapped_prostate_40.csv
./data/mapped/40/mapped_stomach_40.csv
./data/mapped/40/mapped_small_intestine_terminal_ileum_40.csv
./data/mapped/40/mapped_muscle_skeletal_40.csv
./data/mapped/40/mapped_liver_40.csv
./data/mapped/40/mapped_brain_cerebellum_40.csv
./data/mapped/40/mapped_spleen_40.csv
./data/mapped/40/mapped_nerve_tibial_40.csv
./data/mapped/40/mapped_lung_40.csv
./data/mapped/40/mapped_brain_hippocampus_40.csv
./data/mapped/40/mapped_brain_spinal_cord_cervical_c-1)_40.csv
./data/mapped/40/mapped_brain_anterior_cingulate_cortex_ba24_40.csv
./data/mapped/40/mapped_cells_cultured_fibroblasts_40.csv
./data/mapped/40/mapped_testis_40.csv
./data/mapped/40/mapped_brain_cerebellar_hemisphere_40.csv
./data/mapped/40/mapped_minor_salivary_gland_40.csv
./data/mapped/40/mapped_brain_cortex_40.csv
./data/mapped/40/mapped_colon_transverse_40.csv
./data/mapped/40/mapped_skin_sun_exposed_lower_leg_40.csv
./data/mapped/40/mapped_brain_caudate_basal_ganglia_40.csv
./data/mapped/40/mapped_pituitary_40.csv
./data/mapped/40/mapped_heart_left_ventricle_40.csv
./data/mapped/40/mapped_brain_amygdala_40.csv
./data/mapped/40/mapped_artery_aorta_40.csv
./data/mapped/40/mapped_heart_atrial_appendage_40.csv
./data/mapped/40/mapped_colon_sigmoid_40.csv
./data/mapped/40/mapped_brain_frontal_cortex_ba9_40.csv
./data/mapped/40/mapped_thyroid_40.csv
./data/mapped/40/mapped_uterus_40.csv
./data/mapped/40/mapped_cells_ebv-transformed_lymphocytes_40.csv
./data/mapped/40/mapped_esophagus_mucosa_40.csv
./data/mapped/40/mapped_breast_mammary_tissue_40.csv
./data/mapped/40/mapped_artery_coronary_40.csv
./data/mapped/40/mapped_whole_blood_40.csv
./data/mapped/40/mapped_adipose_visceral_omentum_40.csv
./data/mapped/40/mapped_artery_tibial_40.csv
./data/mapped/40/mapped_pancreas_40.csv
./data/mapped/40/mapped_adipose_subcutaneous_40.csv
./data/mapped/40/mapped_brain_nucleus_accumbens_basal ganglia_40.csv

In [32]:
!find . -type f | grep -Ei "\.R$|\.py$|\.ipynb$"

./src/final_visuals.R
./src/gene_networks.R
./src/drug_efficacy.R
./src/normalize_all_tissues.R
./src/normalize_tissue.R
./src/algorithm_0.R
./src/null_algorithm.R
./src/algorithm_1.R
./src/utility.R
./src/drug_efficacy_bpco.R
./src/age_indexing/webscrape.py
./src/age_indexing/compare_algorithms.py
./src/age_indexing/create_visuals.py
./src/age_indexing/z_score_visuals.py
./src/age_based_influence.R

In [33]:
!sed -n '1,220p' src/drug_efficacy_bpco.R

# drug_efficacy.R - takes roughly 9 minutes
# -----------------------------------------------------------
# Input:
#   - Disease genes S (from filtered_neurodegenerative_diseases.csv) for Multiple Sclerosis.
#   - Drug candidate information from filtered_drug_gene_dataset.xlsx:
#         * "Sorted" sheet: Column A = drug name, Column B = gene count (sorted descending).
#         * "Raw" sheet: Column A = drug name, Column B = gene name (may be duplicated).
#
#   For each candidate drug (with at least 20 target genes), we use its full target gene set
#   to calculate efficacy across tissues.
#
#   The efficacy formula for a set of drug targets D is:
#      efficacy(D, S) = ( sum_{s in S'} influence_S_g(graph, D, s, lambda) ) /
#                       ( sum_{n in N'} influence_S_g(graph, D, n, lambda) )
#      where S' is the set of disease genes present in the network and N' is all other genes.
#
#   Output:
#     - A CSV file (data/drug/efficacy.csv) with tissues in rows and a column for each candidate drug.
#
library(igraph)
library(readxl)
source("utility.R")

nd_file <- file.path("..", "data", "drug", "filtered_neurodegenerative_diseases.csv")
if (!file.exists(nd_file)) {
  stop(sprintf("Neurodegenerative diseases file not found: %s", nd_file))
}

# Read the CSV file (adjust header parameter if needed)
nd_data <- read.csv(nd_file, header = FALSE, stringsAsFactors = FALSE)
# Assume Column 1 = gene name, Column 2 = disease name.
disease_genes <- nd_data[nd_data[, 2] == "Multiple Sclerosis", 1]
if (length(disease_genes) == 0) {
  stop("No genes found for 'Multiple Sclerosis' in the neurodegenerative diseases file.")
}
# Clean gene names.
disease_genes <- trimws(disease_genes)

drug_excel_file <- file.path("..", "data", "drug", "filtered_drug_gene_dataset.xlsx")
if (!file.exists(drug_excel_file)) {
  stop(sprintf("Drug Excel file not found: %s", drug_excel_file))
}

# Read the "Sorted" sheet: Column A = drug name, Column B = gene count.
sorted_data <- read_excel(drug_excel_file, sheet = "Sorted", col_names = FALSE)
# Keep only those drugs with a gene count >= 20.
candidate_sorted <- sorted_data[sorted_data[[2]] >= 20, ]
if(nrow(candidate_sorted) == 0) {
  stop("No candidate drugs with gene count >= 20 found in the Sorted sheet.")
}
# Extract candidate drug names.
candidate_drugs <- candidate_sorted[[1]]

# Read the "Raw" sheet: Column A = drug name, Column B = gene name.
raw_data <- read_excel(drug_excel_file, sheet = "Raw", col_names = FALSE)

# Build a named list of candidate drug targets.
# For each candidate drug, retrieve its target genes from the "Raw" sheet.
candidate_drug_targets_list <- lapply(candidate_drugs, function(drug) {
  targets <- raw_data[[2]][raw_data[[1]] == drug]
  unique(trimws(targets))
})
names(candidate_drug_targets_list) <- candidate_drugs

# Compute the intersection count for each candidate drug.
candidate_intersections <- sapply(candidate_drugs, function(drug) {
  targets <- candidate_drug_targets_list[[drug]]
  length(intersect(targets, disease_genes))
})
# Order candidate drugs in descending order of intersection count.
ordered_indices <- order(candidate_intersections, decreasing = TRUE)
# Pick the top n candidate drugs.
top_n <- 270
if(length(ordered_indices) < top_n) {
  top_n <- length(ordered_indices)
}
top_candidate_indices <- ordered_indices[1:top_n]
candidate_drugs <- candidate_drugs[top_candidate_indices]
candidate_drug_targets_list <- candidate_drug_targets_list[candidate_drugs]

cat("Top candidate drugs (with intersection counts):\n")
for(i in seq_along(candidate_drugs)) {
  cat(sprintf("  %s: %d\n", candidate_drugs[i], candidate_intersections[top_candidate_indices[i]]))
}

age_group <- 20
lambda    <- 1

mapped_dir <- file.path("..", "data", "mapped", as.character(age_group))
if (!dir.exists(mapped_dir)) {
  stop(sprintf("Mapped directory does not exist: %s", mapped_dir))
}

mapped_files <- list.files(
  path       = mapped_dir,
  pattern    = paste0("^mapped_.*_", age_group, "\\.csv$"),
  full.names = TRUE
)
if (length(mapped_files) == 0) {
  stop(sprintf("No mapped CSV files found in %s", mapped_dir))
}

drug_dir <- file.path("..", "data", "drug")
if (!dir.exists(drug_dir)) {
  dir.create(drug_dir, recursive = TRUE)
}
output_file <- file.path(drug_dir, "efficacy.csv")

calc_efficacy <- function(graph, drug_targets, disease_genes, non_disease_genes, lambda = 1) {
  valid_drug_targets <- intersect(drug_targets, V(graph)$name)
  if (length(valid_drug_targets) == 0) {
    return(0)
  }

  valid_disease_genes <- intersect(disease_genes, V(graph)$name)
  if (length(valid_disease_genes) == 0) {
    return(0)
  }

  dist_matrix <- distances(graph, v = valid_drug_targets)
  min_distances <- if (length(valid_drug_targets) > 1) {
    apply(dist_matrix, 2, min)
  } else {
    as.vector(dist_matrix)
  }

  influence_values <- exp(-lambda * min_distances)

  numerator <- sum(influence_values[valid_disease_genes])
  denominator <- sum(influence_values[non_disease_genes], na.rm = TRUE)

  if (denominator == 0) {
    return(0)
  }

  return(numerator / denominator)
}


# Header: first column is Tissue-Name, then one column per candidate drug.
efficacy_matrix <- list()
efficacy_matrix[[1]] <- c("Tissue-Name", candidate_drugs)

row_index <- 2  # Row 1 is the header.
for (mapped_file in mapped_files) {
  filename    <- basename(mapped_file)  # e.g., "mapped_brain_cortex_20.csv"
  tissue_name <- sub(paste0("^mapped_(.*)_", age_group, "\\.csv$"), "\\1", filename)

  cat(sprintf("\nProcessing tissue: %s (file=%s)\n", tissue_name, filename))

  edges <- read.csv(mapped_file, header = TRUE, stringsAsFactors = FALSE)
  if (nrow(edges) == 0) {
    # No edges: assign efficacy = 0 for all candidate drugs.
    row_values <- c(tissue_name, rep("0", length(candidate_drugs)))
    efficacy_matrix[[row_index]] <- row_values
    row_index <- row_index + 1
    cat("  --> No edges found, all efficacy=0.\n")
    next
  }

  # Build the tissue network graph.
  g <- graph_from_data_frame(edges, directed = FALSE)
  all_genes <- V(g)$name

  # non_disease_genes: all genes in the network not in the full disease gene list.
  non_disease_genes <- setdiff(all_genes, disease_genes)

  # For each candidate drug, compute the efficacy.
  drug_vals <- character(length(candidate_drugs))
  for (i in seq_along(candidate_drugs)) {
    drug <- candidate_drugs[i]
    targets <- candidate_drug_targets_list[[drug]]

    # Check if at least one target gene is present in this tissue network.
    if (length(intersect(targets, all_genes)) == 0) {
      cat(sprintf("  --> Warning: none of the targets for '%s' found in tissue %s. Setting efficacy=0.\n",
                  drug, tissue_name))
      drug_vals[i] <- "0"
    } else {
      eff_val <- calc_efficacy(g, targets, disease_genes, non_disease_genes, lambda)
      drug_vals[i] <- as.character(eff_val)
    }
  }

  # Build the row for this tissue and add it to the results.
  row_values <- c(tissue_name, drug_vals)
  efficacy_matrix[[row_index]] <- row_values
  row_index <- row_index + 1
}

cat(sprintf("\nWriting CSV to: %s\n", output_file))
file_conn <- file(output_file, open = "w")
for (row_vec in efficacy_matrix) {
  line_str <- paste(row_vec, collapse = ",")
  writeLines(line_str, con = file_conn)
}
close(file_conn)
cat("Done.\n")

In [34]:
!Rscript src/drug_efficacy_bpco.R

Attaching package: ‘igraph’

The following objects are masked from ‘package:stats’:

    decompose, spectrum

The following object is masked from ‘package:base’:

    union

Error in file(filename, "r", encoding = encoding) :
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'utility.R': No such file or directory
Execution halted

In [35]:
%cd /content/Gene-Normalization-and-Mapping/src
!Rscript drug_efficacy_bpco.R

/content/Gene-Normalization-and-Mapping/src

Attaching package: ‘igraph’

The following objects are masked from ‘package:stats’:

    decompose, spectrum

The following object is masked from ‘package:base’:

    union

New names:
• `` -> `...1`
• `` -> `...2`
New names:
• `` -> `...1`
• `` -> `...2`
Top candidate drugs (with intersection counts):
  CYCLOSPORINE: 34
  TRETINOIN: 33
  METHOTREXATE: 31
  ASPIRIN: 30
  PACLITAXEL: 30
  CARBOPLATIN: 26
  CYCLOPHOSPHAMIDE ANHYDROUS: 26
  CYTARABINE: 22
  FLUOROURACIL: 21
  RITUXIMAB: 20
  CLOZAPINE: 20
  DEXAMETHASONE: 20
  TETRADECANOYLPHORBOL ACETATE: 20
  RIBAVIRIN: 20
  PEGINTERFERON ALFA-2B: 20
  SIROLIMUS: 19
  BORTEZOMIB: 19
  VINCRISTINE: 19
  ETOPOSIDE: 19
  GOSSYPOL: 19
  HYDROCORTISONE BUTYRATE: 19
  CARBAMAZEPINE: 19
  ATORVASTATIN CALCIUM TRIHYDRATE: 18
  RESVERATROL: 18
  MASOPROCOL: 18
  INFLIXIMAB-DYYB: 18
  ILORASERTIB: 17
  HALOPERIDOL DECANOATE: 17
  DEHYDRATED ALCOHOL: 17
  DOCETAXEL ANHYDROUS: 17
  ESTRADIOL VALERATE: 17
  PEGINTERFERON ALFA-2A: 17
  NIFEDIPINE: 17
  ANTIDEPRESSANT AGENT: 17
  DOVITINIB: 16
  PAZOPANIB: 16
  TAMOXIFEN: 16
  QUERCETIN: 16
  CURCUMIN: 16
  EPOETIN ALFA: 16
  CHEMBL:CHEMBL429095: 16
  DOXYCYCLINE ANHYDROUS: 16
  GEMCITABINE: 15
  DAUNORUBICIN LIPOSOMAL: 15
  RALOXIFENE HYDROCHLORIDE: 15
  TESTOSTERONE: 15
  ADALIMUMAB-ADBM: 15
  MITOXANTRONE: 15
  OLANZAPINE: 14
  ERLOTINIB: 14
  RG-1530: 14
  PROGESTERONE: 14
  SIMVASTATIN: 14
  ALDESLEUKIN: 14
  COLCHICINE: 14
  PREDNISONE: 14
  STAUROSPORINE: 14
  IMATINIB: 13
  CENISERTIB: 13
  GEFITINIB: 13
  GENISTEIN: 13
  INDOMETHACIN: 13
  DISULFIRAM: 13
  LEVODOPA: 13
  THALIDOMIDE: 13
  CAFFEINE: 13
  LITHIUM: 13
  PRAVASTATIN SODIUM: 13
  SUNITINIB: 12
  PF-562271: 12
  NVP-TAE684: 12
  VALPROIC ACID: 12
  PEMBROLIZUMAB: 12
  SP-600125: 12
  CELECOXIB: 12
  LOVASTATIN: 12
  ACETAMINOPHEN: 12
  STREPTOZOCIN: 12
  PHENYTOIN SODIUM: 12
  WORTMANNIN: 12
  CAMPTOTHECIN: 12
  METHIMAZOLE: 12
  SODIUM CHLORIDE: 12
  TROGLITAZONE: 12
  DASATINIB ANHYDROUS: 11
  ENTRECTINIB: 11
  NICOTINE POLACRILEX: 11
  CETUXIMAB: 11
  DESIPRAMINE: 11
  IBUPROFEN, SODIUM SALT: 11
  CHLORPROMAZINE: 11
  DICLOFENAC SODIUM: 11
  OXALIPLATIN: 11
  BEVACIZUMAB-AWWB: 11
  DACTINOMYCIN: 11
  MERCAPTOPURINE: 11
  CHEMBL:CHEMBL505670: 11
  LAPATINIB: 10
  LINIFANIB: 10
  CEDIRANIB: 10
  RISPERIDONE: 10
  EPINEPHRINE: 10
  CYC-116: 10
  ISOPROTERENOL: 10
  PD-0166285: 10
  DIETHYLSTILBESTROL: 10
  BROMOCRIPTINE: 10
  PROPRANOLOL HYDROCHLORIDE: 10
  HEXACHLOROPHENE: 10
  IDARUBICIN: 10
  PROCHLORPERAZINE: 10
  APIGENIN: 10
  INTERFERON ALFA-2B: 10
  SURAMIN: 10
  SULFASALAZINE: 10
  LUTEOLIN: 10
  PAREGORIC: 10
  PREDNISOLONE: 10
  PROPYLTHIOURACIL: 10
  OLAPARIB: 9
  DOXEPIN HYDROCHLORIDE: 9
  TOZASERTIB: 9
  IRINOTECAN HYDROCHLORIDE: 9
  NIVOLUMAB: 9
  HESPERADIN: 9
  THERAPEUTIC HORMONE: 9
  AZACITIDINE: 9
  TRICHOSTATIN A: 9
  USTEKINUMAB: 9
  DOPAMINE: 9
  HYDROCHLOROTHIAZIDE: 9
  THERAPEUTIC GLUCOCORTICOID: 9
  TYROSINE KINASE INHIBITOR: 9
  DECITABINE: 9
  FENOFIBRATE MICRONIZED: 9
  MARIMASTAT: 9
  TRIAMCINOLONE: 9
  VITAMIN K3: 9
  THEOPHYLLINE: 9
  VINORELBINE: 9
  TAMATINIB: 8
  VORINOSTAT: 8
  THIORIDAZINE: 8
  CARVEDILOL: 8
  AMITRIPTYLINE HYDROCHLORIDE: 8
  APOMORPHINE: 8
  CLOMIPRAMINE: 8
  LIOTHYRONINE: 8
  HEPARIN: 8
  CAPECITABINE: 8
  JNJ-7706621: 8
  NORTRIPTYLINE: 8
  IPILIMUMAB: 8
  TRIFLUOPERAZINE: 8
  ARSENIC TRIOXIDE: 8
  MONOAMINE OXIDASE INHIBITOR: 8
  FENRETINIDE: 8
  FLUPHENAZINE HYDROCHLORIDE: 8
  MIFEPRISTONE: 8
  CHEMBL:CHEMBL19954: 8
  CHEMBL:CHEMBL596633: 8
  CLAVULANIC ACID: 8
  FLOXACILLIN: 8
  PROTEIN KINASE C INHIBITOR: 8
  PALBOCICLIB: 7
  INSULIN, REGULAR, HUMAN: 7
  PHENOBARBITAL: 7
  GW441756X: 7
  CARFILZOMIB: 7
  ENMD-2076: 7
  NOREPINEPHRINE: 7
  MIDOSTAURIN: 7
  MESALAMINE: 7
  METHYLPHENIDATE HYDROCHLORIDE: 7
  PIMOZIDE: 7
  ALSTERPAULLONE: 7
  PEMETREXED DISODIUM: 7
  MELATONIN: 7
  PROMETHAZINE HYDROCHLORIDE: 7
  RETINOIC ACID AGENT: 7
  VITAMIN A: 7
  LEUCOVORIN CALCIUM: 7
  THROMBIN: 7
  IXAZOMIB: 7
  CHEMBL:CHEMBL493863: 7
  CHEMBL:CHEMBL547833: 7
  DACTOLISIB: 6
  NINTEDANIB ESYLATE: 6
  TRAMETINIB DIMETHYL SULFOXIDE: 6
  CRIZOTINIB: 6
  FULVESTRANT: 6
  ALITRETINOIN: 6
  METFORMIN: 6
  GO-6976: 6
  RUXOLITINIB: 6
  TALAZOPARIB: 6
  FLUOXETINE HYDROCHLORIDE: 6
  CP-547632: 6
  TRIMIPRAMINE: 6
  RABEPRAZOLE: 6
  CHEMBL:CHEMBL546797: 6
  NAPROXEN SODIUM: 6
  NIRAPARIB: 6
  PERPHENAZINE: 6
  WARFARIN: 6
  ATENOLOL: 6
  MK-2461: 6
  SPIRONOLACTONE: 6
  ACID BLUE 129: 6
  ADENOVIRUS VECTOR: 6
  ALLOPURINOL: 6
  BENSERAZIDE HYDROCHLORIDE: 6
  CHELERYTHRINE: 6
  CHEMBL:CHEMBL234338: 6
  CHEMBL:CHEMBL580421: 6
  DIACETYLRHEIN: 6
  DOCEBENONE: 6
  EUFLAVINE: 6
  FAS LIGAND: 6
  GM-CSF: 6
  ISOVELLERAL: 6
  ITRACONAZOLE: 6
  MECHLORETHAMINE: 6
  METHYLENE BLUE ANHYDROUS: 6
  MORIN: 6
  NOCODAZOLE: 6
  OCHRATOXIN A: 6
  OXIDOPAMINE HYDROCHLORIDE: 6
  PREGNANT MARE SERUM GONADOTROPIN: 6
  RECOMBINANT 70-KD HEAT-SHOCK PROTEIN: 6
  STAVUDINE: 6
  2-METHOXYESTRADIOL: 6
  APOMORPHINE HYDROCHLORIDE HEMIHYDRATE: 6
  CHEMBL:CHEMBL1362503: 6
  CHEMBL:CHEMBL584458: 6
  CHEMBL:CHEMBL601757: 6
  DRUGSATFDA.NDA:008378: 6
  FLUPIRTINE: 6
  KEPONE: 6
  PROPYLPYRAZOLETRIOL: 6
  PROTOAPIGENONE: 6
  PUROMYCIN: 6
  PYRAZINAMIDE: 6
  CHEMBL:CHEMBL585502: 6
  CHEMBL:CHEMBL602127: 6
  CHEMBL:CHEMBL609606: 6
  GLATIRAMER: 6
  PINAFIDE: 6
  2'-HYDROXYCHALCONE: 6
  CHEMBL:CHEMBL124006: 6
  CHEMBL:CHEMBL1312050: 6
  CHEMBL:CHEMBL22062: 6
  CTS-1027: 6
  VINCRISTINE SULFATE: 6
  VANDETANIB: 5
  AFATINIB: 5
  VATALANIB: 5
  AXITINIB: 5
  PROMAZINE: 5
  VEMURAFENIB: 5
  ATEZOLIZUMAB: 5
  CITALOPRAM: 5
  PANOBINOSTAT: 5
  RUCAPARIB: 5
  TOPIRAMATE: 5
  ALVOCIDIB: 5
  MIDAZOLAM HYDROCHLORIDE: 5
  VELIPARIB: 5
  OSIMERTINIB: 5
  ILOPERIDONE: 5

Processing tissue: adipose_subcutaneous (file=mapped_adipose_subcutaneous_20.csv)

Processing tissue: adipose_visceral_omentum (file=mapped_adipose_visceral_omentum_20.csv)

Processing tissue: adrenal_gland (file=mapped_adrenal_gland_20.csv)

Processing tissue: artery_aorta (file=mapped_artery_aorta_20.csv)

Processing tissue: artery_coronary (file=mapped_artery_coronary_20.csv)

Processing tissue: artery_tibial (file=mapped_artery_tibial_20.csv)

Processing tissue: brain_amygdala (file=mapped_brain_amygdala_20.csv)

Processing tissue: brain_anterior_cingulate_cortex_ba24 (file=mapped_brain_anterior_cingulate_cortex_ba24_20.csv)

Processing tissue: brain_caudate_basal_ganglia (file=mapped_brain_caudate_basal_ganglia_20.csv)

Processing tissue: brain_cerebellar_hemisphere (file=mapped_brain_cerebellar_hemisphere_20.csv)

Processing tissue: brain_cerebellum (file=mapped_brain_cerebellum_20.csv)

Processing tissue: brain_cortex (file=mapped_brain_cortex_20.csv)

Processing tissue: brain_frontal_cortex_ba9 (file=mapped_brain_frontal_cortex_ba9_20.csv)

Processing tissue: brain_hippocampus (file=mapped_brain_hippocampus_20.csv)

Processing tissue: brain_hypothalamus (file=mapped_brain_hypothalamus_20.csv)

Processing tissue: brain_nucleus_accumbens_basal ganglia (file=mapped_brain_nucleus_accumbens_basal ganglia_20.csv)

Processing tissue: brain_putamen_basal_ganglia (file=mapped_brain_putamen_basal_ganglia_20.csv)

Processing tissue: brain_spinal_cord_cervical_c-1) (file=mapped_brain_spinal_cord_cervical_c-1)_20.csv)

Processing tissue: brain_substantia_nigra (file=mapped_brain_substantia_nigra_20.csv)

Processing tissue: breast_mammary_tissue (file=mapped_breast_mammary_tissue_20.csv)

Processing tissue: cells_cultured_fibroblasts (file=mapped_cells_cultured_fibroblasts_20.csv)

Processing tissue: cells_ebv-transformed_lymphocytes (file=mapped_cells_ebv-transformed_lymphocytes_20.csv)

Processing tissue: colon_sigmoid (file=mapped_colon_sigmoid_20.csv)

Processing tissue: colon_transverse (file=mapped_colon_transverse_20.csv)

Processing tissue: esophagus_gastroesophageal_junction (file=mapped_esophagus_gastroesophageal_junction_20.csv)

Processing tissue: esophagus_mucosa (file=mapped_esophagus_mucosa_20.csv)

Processing tissue: esophagus_muscularis (file=mapped_esophagus_muscularis_20.csv)

Processing tissue: heart_atrial_appendage (file=mapped_heart_atrial_appendage_20.csv)

Processing tissue: heart_left_ventricle (file=mapped_heart_left_ventricle_20.csv)

Processing tissue: liver (file=mapped_liver_20.csv)

Processing tissue: lung (file=mapped_lung_20.csv)

Processing tissue: minor_salivary_gland (file=mapped_minor_salivary_gland_20.csv)

Processing tissue: muscle_skeletal (file=mapped_muscle_skeletal_20.csv)

Processing tissue: nerve_tibial (file=mapped_nerve_tibial_20.csv)

Processing tissue: ovary (file=mapped_ovary_20.csv)

Processing tissue: pancreas (file=mapped_pancreas_20.csv)

Processing tissue: pituitary (file=mapped_pituitary_20.csv)

Processing tissue: prostate (file=mapped_prostate_20.csv)

Processing tissue: skin_not_sun_exposed_suprapubic (file=mapped_skin_not_sun_exposed_suprapubic_20.csv)

Processing tissue: skin_sun_exposed_lower_leg (file=mapped_skin_sun_exposed_lower_leg_20.csv)

Processing tissue: small_intestine_terminal_ileum (file=mapped_small_intestine_terminal_ileum_20.csv)

Processing tissue: spleen (file=mapped_spleen_20.csv)

Processing tissue: stomach (file=mapped_stomach_20.csv)

Processing tissue: testis (file=mapped_testis_20.csv)

Processing tissue: thyroid (file=mapped_thyroid_20.csv)

Processing tissue: uterus (file=mapped_uterus_20.csv)

Processing tissue: vagina (file=mapped_vagina_20.csv)

Processing tissue: whole_blood (file=mapped_whole_blood_20.csv)

Writing CSV to: ../data/drug/efficacy.csv
Done.

In [36]:
%cd /content/Gene-Normalization-and-Mapping
!grep -n "diabetes\|bpco\|disease\|drug_gene\|read.csv\|write.csv\|source" src/drug_efficacy_bpco.R

/content/Gene-Normalization-and-Mapping
4:#   - Disease genes S (from filtered_neurodegenerative_diseases.csv) for Multiple Sclerosis.
5:#   - Drug candidate information from filtered_drug_gene_dataset.xlsx:
15:#      where S' is the set of disease genes present in the network and N' is all other genes.
22:source("utility.R")
24:nd_file <- file.path("..", "data", "drug", "filtered_neurodegenerative_diseases.csv")
26:  stop(sprintf("Neurodegenerative diseases file not found: %s", nd_file))
30:nd_data <- read.csv(nd_file, header = FALSE, stringsAsFactors = FALSE)
31:# Assume Column 1 = gene name, Column 2 = disease name.
32:disease_genes <- nd_data[nd_data[, 2] == "Multiple Sclerosis", 1]
33:if (length(disease_genes) == 0) {
34:  stop("No genes found for 'Multiple Sclerosis' in the neurodegenerative diseases file.")
37:disease_genes <- trimws(disease_genes)
39:drug_excel_file <- file.path("..", "data", "drug", "filtered_drug_gene_dataset.xlsx")
68:  length(intersect(targets, disease_genes))
109:calc_efficacy <- function(graph, drug_targets, disease_genes, non_disease_genes, lambda = 1) {
115:  valid_disease_genes <- intersect(disease_genes, V(graph)$name)
116:  if (length(valid_disease_genes) == 0) {
129:  numerator <- sum(influence_values[valid_disease_genes])
130:  denominator <- sum(influence_values[non_disease_genes], na.rm = TRUE)
151:  edges <- read.csv(mapped_file, header = TRUE, stringsAsFactors = FALSE)
165:  # non_disease_genes: all genes in the network not in the full disease gene list.
166:  non_disease_genes <- setdiff(all_genes, disease_genes)
180:      eff_val <- calc_efficacy(g, targets, disease_genes, non_disease_genes, lambda)

In [37]:
!find . -type f -printf "%TY-%Tm-%Td %TH:%TM  %p\n" | grep -Ei "bpco|diabetes|efficacy|matrix|csv" | sort

2026-06-21 18:53  ./data/bpco_drug_gene_associations.csv
2026-06-21 18:53  ./data/bpco_gene_disease_associations.csv
2026-06-21 19:05  ./data/drug/efficacy-alzheimers.csv
2026-06-21 19:05  ./data/drug/efficacy-multiple sclerosis.csv
2026-06-21 19:05  ./data/drug/efficacy-parkinson.csv
2026-06-21 19:05  ./data/drug/filtered_drug_gene_dataset.csv
2026-06-21 19:05  ./data/drug/filtered_neurodegenerative_diseases.csv
2026-06-21 19:05  ./data/mapped/20/mapped_adipose_subcutaneous_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_adipose_visceral_omentum_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_adrenal_gland_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_artery_aorta_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_artery_coronary_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_artery_tibial_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_brain_amygdala_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_brain_anterior_cingulate_cortex_ba24_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_brain_caudate_basal_ganglia_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_brain_cerebellar_hemisphere_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_brain_cerebellum_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_brain_cortex_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_brain_frontal_cortex_ba9_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_brain_hippocampus_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_brain_hypothalamus_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_brain_nucleus_accumbens_basal ganglia_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_brain_putamen_basal_ganglia_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_brain_spinal_cord_cervical_c-1)_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_brain_substantia_nigra_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_breast_mammary_tissue_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_cells_cultured_fibroblasts_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_cells_ebv-transformed_lymphocytes_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_colon_sigmoid_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_colon_transverse_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_esophagus_gastroesophageal_junction_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_esophagus_mucosa_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_esophagus_muscularis_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_heart_atrial_appendage_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_heart_left_ventricle_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_liver_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_lung_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_minor_salivary_gland_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_muscle_skeletal_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_nerve_tibial_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_ovary_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_pancreas_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_pituitary_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_prostate_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_skin_not_sun_exposed_suprapubic_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_skin_sun_exposed_lower_leg_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_small_intestine_terminal_ileum_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_spleen_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_stomach_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_testis_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_thyroid_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_uterus_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_vagina_20.csv
2026-06-21 19:05  ./data/mapped/20/mapped_whole_blood_20.csv
2026-06-21 19:05  ./data/mapped/30/mapped_adipose_subcutaneous_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_adipose_visceral_omentum_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_adrenal_gland_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_artery_aorta_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_artery_coronary_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_artery_tibial_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_brain_amygdala_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_brain_anterior_cingulate_cortex_ba24_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_brain_caudate_basal_ganglia_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_brain_cerebellar_hemisphere_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_brain_cerebellum_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_brain_cortex_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_brain_frontal_cortex_ba9_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_brain_hippocampus_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_brain_hypothalamus_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_brain_nucleus_accumbens_basal ganglia_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_brain_putamen_basal_ganglia_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_brain_spinal_cord_cervical_c-1)_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_brain_substantia_nigra_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_breast_mammary_tissue_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_cells_cultured_fibroblasts_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_cells_ebv-transformed_lymphocytes_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_colon_sigmoid_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_colon_transverse_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_esophagus_gastroesophageal_junction_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_esophagus_mucosa_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_esophagus_muscularis_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_heart_atrial_appendage_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_heart_left_ventricle_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_liver_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_lung_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_minor_salivary_gland_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_muscle_skeletal_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_nerve_tibial_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_ovary_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_pancreas_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_pituitary_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_prostate_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_skin_not_sun_exposed_suprapubic_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_skin_sun_exposed_lower_leg_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_small_intestine_terminal_ileum_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_spleen_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_stomach_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_testis_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_thyroid_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_uterus_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_vagina_30.csv
2026-06-21 19:05  ./data/mapped/30/mapped_whole_blood_30.csv
2026-06-21 19:05  ./data/mapped/40/mapped_adipose_subcutaneous_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_adipose_visceral_omentum_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_adrenal_gland_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_artery_aorta_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_artery_coronary_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_artery_tibial_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_brain_amygdala_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_brain_anterior_cingulate_cortex_ba24_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_brain_caudate_basal_ganglia_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_brain_cerebellar_hemisphere_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_brain_cerebellum_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_brain_cortex_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_brain_frontal_cortex_ba9_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_brain_hippocampus_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_brain_hypothalamus_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_brain_nucleus_accumbens_basal ganglia_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_brain_putamen_basal_ganglia_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_brain_spinal_cord_cervical_c-1)_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_brain_substantia_nigra_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_breast_mammary_tissue_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_cells_cultured_fibroblasts_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_cells_ebv-transformed_lymphocytes_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_colon_sigmoid_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_colon_transverse_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_esophagus_gastroesophageal_junction_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_esophagus_mucosa_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_esophagus_muscularis_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_heart_atrial_appendage_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_heart_left_ventricle_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_liver_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_lung_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_minor_salivary_gland_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_muscle_skeletal_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_nerve_tibial_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_ovary_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_pancreas_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_pituitary_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_prostate_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_skin_not_sun_exposed_suprapubic_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_skin_sun_exposed_lower_leg_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_small_intestine_terminal_ileum_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_spleen_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_stomach_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_testis_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_thyroid_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_uterus_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_vagina_40.csv
2026-06-21 19:05  ./data/mapped/40/mapped_whole_blood_40.csv
2026-06-21 19:05  ./data/mapped/50/mapped_adipose_subcutaneous_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_adipose_visceral_omentum_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_adrenal_gland_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_artery_aorta_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_artery_coronary_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_artery_tibial_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_brain_amygdala_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_brain_anterior_cingulate_cortex_ba24_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_brain_caudate_basal_ganglia_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_brain_cerebellar_hemisphere_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_brain_cerebellum_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_brain_cortex_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_brain_frontal_cortex_ba9_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_brain_hippocampus_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_brain_hypothalamus_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_brain_nucleus_accumbens_basal ganglia_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_brain_putamen_basal_ganglia_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_brain_spinal_cord_cervical_c-1)_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_brain_substantia_nigra_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_breast_mammary_tissue_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_cells_cultured_fibroblasts_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_cells_ebv-transformed_lymphocytes_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_colon_sigmoid_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_colon_transverse_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_esophagus_gastroesophageal_junction_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_esophagus_mucosa_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_esophagus_muscularis_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_heart_atrial_appendage_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_heart_left_ventricle_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_liver_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_lung_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_minor_salivary_gland_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_muscle_skeletal_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_nerve_tibial_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_ovary_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_pancreas_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_pituitary_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_prostate_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_skin_not_sun_exposed_suprapubic_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_skin_sun_exposed_lower_leg_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_small_intestine_terminal_ileum_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_spleen_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_stomach_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_testis_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_thyroid_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_uterus_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_vagina_50.csv
2026-06-21 19:05  ./data/mapped/50/mapped_whole_blood_50.csv
2026-06-21 19:05  ./data/mapped/60/mapped_adipose_subcutaneous_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_adipose_visceral_omentum_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_adrenal_gland_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_artery_aorta_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_artery_coronary_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_artery_tibial_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_brain_amygdala_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_brain_anterior_cingulate_cortex_ba24_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_brain_caudate_basal_ganglia_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_brain_cerebellar_hemisphere_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_brain_cerebellum_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_brain_cortex_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_brain_frontal_cortex_ba9_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_brain_hippocampus_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_brain_hypothalamus_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_brain_nucleus_accumbens_basal ganglia_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_brain_putamen_basal_ganglia_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_brain_spinal_cord_cervical_c-1)_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_brain_substantia_nigra_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_breast_mammary_tissue_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_cells_cultured_fibroblasts_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_cells_ebv-transformed_lymphocytes_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_colon_sigmoid_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_colon_transverse_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_esophagus_gastroesophageal_junction_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_esophagus_mucosa_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_esophagus_muscularis_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_heart_atrial_appendage_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_heart_left_ventricle_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_liver_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_lung_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_minor_salivary_gland_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_muscle_skeletal_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_nerve_tibial_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_ovary_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_pancreas_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_pituitary_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_prostate_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_skin_not_sun_exposed_suprapubic_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_skin_sun_exposed_lower_leg_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_small_intestine_terminal_ileum_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_spleen_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_stomach_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_testis_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_thyroid_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_uterus_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_vagina_60.csv
2026-06-21 19:05  ./data/mapped/60/mapped_whole_blood_60.csv
2026-06-21 19:05  ./data/mapped/70/mapped_adipose_subcutaneous_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_adipose_visceral_omentum_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_adrenal_gland_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_artery_aorta_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_artery_coronary_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_artery_tibial_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_brain_amygdala_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_brain_anterior_cingulate_cortex_ba24_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_brain_caudate_basal_ganglia_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_brain_cerebellar_hemisphere_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_brain_cerebellum_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_brain_cortex_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_brain_frontal_cortex_ba9_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_brain_hippocampus_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_brain_hypothalamus_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_brain_nucleus_accumbens_basal ganglia_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_brain_putamen_basal_ganglia_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_brain_spinal_cord_cervical_c-1)_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_brain_substantia_nigra_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_breast_mammary_tissue_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_cells_cultured_fibroblasts_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_cells_ebv-transformed_lymphocytes_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_colon_sigmoid_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_colon_transverse_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_esophagus_gastroesophageal_junction_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_esophagus_mucosa_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_esophagus_muscularis_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_heart_atrial_appendage_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_heart_left_ventricle_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_liver_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_lung_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_minor_salivary_gland_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_muscle_skeletal_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_nerve_tibial_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_ovary_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_pancreas_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_pituitary_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_prostate_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_skin_not_sun_exposed_suprapubic_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_skin_sun_exposed_lower_leg_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_small_intestine_terminal_ileum_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_spleen_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_stomach_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_testis_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_thyroid_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_uterus_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_vagina_70.csv
2026-06-21 19:05  ./data/mapped/70/mapped_whole_blood_70.csv
2026-06-21 19:05  ./data/normalized/normalized_adipose_subcutaneous.csv

In [38]:
!grep -n "bpco_gene_disease_associations.csv\|bpco_drug_gene_associations.csv" src/drug_efficacy_bpco.R

In [39]:
%cd /content/Gene-Normalization-and-Mapping
!sed -n '1,260p' src/drug_efficacy_bpco.R

/content/Gene-Normalization-and-Mapping
# drug_efficacy.R - takes roughly 9 minutes
# -----------------------------------------------------------
# Input:
#   - Disease genes S (from filtered_neurodegenerative_diseases.csv) for Multiple Sclerosis.
#   - Drug candidate information from filtered_drug_gene_dataset.xlsx:
#         * "Sorted" sheet: Column A = drug name, Column B = gene count (sorted descending).
#         * "Raw" sheet: Column A = drug name, Column B = gene name (may be duplicated).
#
#   For each candidate drug (with at least 20 target genes), we use its full target gene set
#   to calculate efficacy across tissues.
#
#   The efficacy formula for a set of drug targets D is:
#      efficacy(D, S) = ( sum_{s in S'} influence_S_g(graph, D, s, lambda) ) /
#                       ( sum_{n in N'} influence_S_g(graph, D, n, lambda) )
#      where S' is the set of disease genes present in the network and N' is all other genes.
#
#   Output:
#     - A CSV file (data/drug/efficacy.csv) with tissues in rows and a column for each candidate drug.
#
library(igraph)
library(readxl)
source("utility.R")

nd_file <- file.path("..", "data", "drug", "filtered_neurodegenerative_diseases.csv")
if (!file.exists(nd_file)) {
  stop(sprintf("Neurodegenerative diseases file not found: %s", nd_file))
}

# Read the CSV file (adjust header parameter if needed)
nd_data <- read.csv(nd_file, header = FALSE, stringsAsFactors = FALSE)
# Assume Column 1 = gene name, Column 2 = disease name.
disease_genes <- nd_data[nd_data[, 2] == "Multiple Sclerosis", 1]
if (length(disease_genes) == 0) {
  stop("No genes found for 'Multiple Sclerosis' in the neurodegenerative diseases file.")
}
# Clean gene names.
disease_genes <- trimws(disease_genes)

drug_excel_file <- file.path("..", "data", "drug", "filtered_drug_gene_dataset.xlsx")
if (!file.exists(drug_excel_file)) {
  stop(sprintf("Drug Excel file not found: %s", drug_excel_file))
}

# Read the "Sorted" sheet: Column A = drug name, Column B = gene count.
sorted_data <- read_excel(drug_excel_file, sheet = "Sorted", col_names = FALSE)
# Keep only those drugs with a gene count >= 20.
candidate_sorted <- sorted_data[sorted_data[[2]] >= 20, ]
if(nrow(candidate_sorted) == 0) {
  stop("No candidate drugs with gene count >= 20 found in the Sorted sheet.")
}
# Extract candidate drug names.
candidate_drugs <- candidate_sorted[[1]]

# Read the "Raw" sheet: Column A = drug name, Column B = gene name.
raw_data <- read_excel(drug_excel_file, sheet = "Raw", col_names = FALSE)

# Build a named list of candidate drug targets.
# For each candidate drug, retrieve its target genes from the "Raw" sheet.
candidate_drug_targets_list <- lapply(candidate_drugs, function(drug) {
  targets <- raw_data[[2]][raw_data[[1]] == drug]
  unique(trimws(targets))
})
names(candidate_drug_targets_list) <- candidate_drugs

# Compute the intersection count for each candidate drug.
candidate_intersections <- sapply(candidate_drugs, function(drug) {
  targets <- candidate_drug_targets_list[[drug]]
  length(intersect(targets, disease_genes))
})
# Order candidate drugs in descending order of intersection count.
ordered_indices <- order(candidate_intersections, decreasing = TRUE)
# Pick the top n candidate drugs.
top_n <- 270
if(length(ordered_indices) < top_n) {
  top_n <- length(ordered_indices)
}
top_candidate_indices <- ordered_indices[1:top_n]
candidate_drugs <- candidate_drugs[top_candidate_indices]
candidate_drug_targets_list <- candidate_drug_targets_list[candidate_drugs]

cat("Top candidate drugs (with intersection counts):\n")
for(i in seq_along(candidate_drugs)) {
  cat(sprintf("  %s: %d\n", candidate_drugs[i], candidate_intersections[top_candidate_indices[i]]))
}

age_group <- 20
lambda    <- 1

mapped_dir <- file.path("..", "data", "mapped", as.character(age_group))
if (!dir.exists(mapped_dir)) {
  stop(sprintf("Mapped directory does not exist: %s", mapped_dir))
}

mapped_files <- list.files(
  path       = mapped_dir,
  pattern    = paste0("^mapped_.*_", age_group, "\\.csv$"),
  full.names = TRUE
)
if (length(mapped_files) == 0) {
  stop(sprintf("No mapped CSV files found in %s", mapped_dir))
}

drug_dir <- file.path("..", "data", "drug")
if (!dir.exists(drug_dir)) {
  dir.create(drug_dir, recursive = TRUE)
}
output_file <- file.path(drug_dir, "efficacy.csv")

calc_efficacy <- function(graph, drug_targets, disease_genes, non_disease_genes, lambda = 1) {
  valid_drug_targets <- intersect(drug_targets, V(graph)$name)
  if (length(valid_drug_targets) == 0) {
    return(0)
  }

  valid_disease_genes <- intersect(disease_genes, V(graph)$name)
  if (length(valid_disease_genes) == 0) {
    return(0)
  }

  dist_matrix <- distances(graph, v = valid_drug_targets)
  min_distances <- if (length(valid_drug_targets) > 1) {
    apply(dist_matrix, 2, min)
  } else {
    as.vector(dist_matrix)
  }

  influence_values <- exp(-lambda * min_distances)

  numerator <- sum(influence_values[valid_disease_genes])
  denominator <- sum(influence_values[non_disease_genes], na.rm = TRUE)

  if (denominator == 0) {
    return(0)
  }

  return(numerator / denominator)
}


# Header: first column is Tissue-Name, then one column per candidate drug.
efficacy_matrix <- list()
efficacy_matrix[[1]] <- c("Tissue-Name", candidate_drugs)

row_index <- 2  # Row 1 is the header.
for (mapped_file in mapped_files) {
  filename    <- basename(mapped_file)  # e.g., "mapped_brain_cortex_20.csv"
  tissue_name <- sub(paste0("^mapped_(.*)_", age_group, "\\.csv$"), "\\1", filename)

  cat(sprintf("\nProcessing tissue: %s (file=%s)\n", tissue_name, filename))

  edges <- read.csv(mapped_file, header = TRUE, stringsAsFactors = FALSE)
  if (nrow(edges) == 0) {
    # No edges: assign efficacy = 0 for all candidate drugs.
    row_values <- c(tissue_name, rep("0", length(candidate_drugs)))
    efficacy_matrix[[row_index]] <- row_values
    row_index <- row_index + 1
    cat("  --> No edges found, all efficacy=0.\n")
    next
  }

  # Build the tissue network graph.
  g <- graph_from_data_frame(edges, directed = FALSE)
  all_genes <- V(g)$name

  # non_disease_genes: all genes in the network not in the full disease gene list.
  non_disease_genes <- setdiff(all_genes, disease_genes)

  # For each candidate drug, compute the efficacy.
  drug_vals <- character(length(candidate_drugs))
  for (i in seq_along(candidate_drugs)) {
    drug <- candidate_drugs[i]
    targets <- candidate_drug_targets_list[[drug]]

    # Check if at least one target gene is present in this tissue network.
    if (length(intersect(targets, all_genes)) == 0) {
      cat(sprintf("  --> Warning: none of the targets for '%s' found in tissue %s. Setting efficacy=0.\n",
                  drug, tissue_name))
      drug_vals[i] <- "0"
    } else {
      eff_val <- calc_efficacy(g, targets, disease_genes, non_disease_genes, lambda)
      drug_vals[i] <- as.character(eff_val)
    }
  }

  # Build the row for this tissue and add it to the results.
  row_values <- c(tissue_name, drug_vals)
  efficacy_matrix[[row_index]] <- row_values
  row_index <- row_index + 1
}

cat(sprintf("\nWriting CSV to: %s\n", output_file))
file_conn <- file(output_file, open = "w")
for (row_vec in efficacy_matrix) {
  line_str <- paste(row_vec, collapse = ",")
  writeLines(line_str, con = file_conn)
}
close(file_conn)
cat("Done.\n")